### ISSUE TITLE
Integration avec Nuxt

### ISSUE THREAD

**Issue by vinyll** [dnum-mi/vue-dsfr#132]
Est-ce possible d'intégrer le vue-dsfr dans un nouveau projet Nuxt?

**Comment by laruiss** [comment]
Bonjour, désolé pour le délai de réponse. Nous tâcherons d'être plus réactifs prochainement.

Cette bibliothèque est pour Vue 3. Or si vous utilisez Nuxt 2, vous utilisez Vue 2.

Il faut utiliser Nuxt 3 pour utiliser cette bibilothèque.

Bon courage !

**Comment by laruiss** [comment]
Bonjour @vinyll 
Nous avons remarqué que vous aviez changé votre message pour préciser que vous utilisiez bien Nuxt3. J'ai donc rouvert l'issue.

La bibliothèque VueDsfr fournit bien plusieurs build (esm et umd entre autres) et Nuxt3 sait lequel choisir.

Cependant nous utilisons la bibliothèque oh-vue-icons avec leur build ESM pour être sûr de n'embarquer que les icônes utilisées. Il faut donc 
Voici la solution : il faut dire à Nuxt de transpiler `oh-vue-icons` en ajoutant ceci dans votre `nuxt.config.js` :

```diff
import { defineNuxtConfig } from 'nuxt3';

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
 export default defineNuxtConfig({
+  build: {
+    transpile: [
+      'oh-vue-icons/dist/v3/icon.es',
+      'oh-vue-icons/icons/ri/index.js',
+    ],
+  },
});
```

[Un exemple ici](https://stackblitz.com/edit/nuxt-starter-suunj6?file=app.vue)

**Comment by vinyll** [comment]
Merci pour ce retour.
Je n'ai pas changé mon message depuis le 25 oct par contre, c'était bien toujours avec Nuxt3 dont il était question.

Nous sommes [partis sur l'intégration du DSFR natif](https://github.com/incubateur-territoires/incubateur.anct.gouv.fr/blob/nuxt-dsfr/nuxt.config.ts), mais je regarde les exemples prochainement pour reconsidérer cette extension.

:+1:

**Comment by laruiss** [comment]
OK, voilà, c'est dans la [doc officielle](https://vue-dsfr.netlify.app/?path=/story/docs-2-guide-d-utilisation--page), désormais.

**Comment by vinyll** [comment]
Super, ca roule maintenant.

Il y a quand même des petites étapes qu'on devine par l'exemple et qui ne sont pas documentées :

Rendre accessible les componsants VueDsfr dans Nuxt :

Créer un fichier _plugins/vue-dsfr.js_ :

```
import { defineNuxtPlugin } from '#app';
import VueDsfr from '@laruiss/vue-dsfr';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VueDsfr);
});
```

Importer les CSS globalement via _nuxt.config.ts_ (en plus du `build` pour les icones mentionné dans la doc) :
```
export default defineNuxtConfig({
  css: [
    '@laruiss/vue-dsfr/dist/vue-dsfr-fonts.css',
    '@laruiss/vue-dsfr/dist/vue-dsfr.css',
  ],
  …
```

Une fois qu'on a compris ça, ça semble fluide 🛼 

Merci :)
