### ISSUE TITLE
Optional Chaining errors

### ISSUE THREAD

**Issue by THouriezPEReN** [dnum-mi/vue-dsfr#152]
Bonjour,

En utilisant une configuration de projet vue3 par défaut (babel / eslint) et avec:

- npm en version 8.1.0
- node en version 16.13.0
- nodejs en version 12.22.5 (v stable sur machine débian)

Après avoir installé votre plugin et en tentant de lancer le projet en local j'obtiens systématiquement une erreur:
```
...
Module parse failed: Unexpected token (1406:31)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       validator: (networks) =>
|         networks.every(
>           (network) => network?.name && network.href && allowedNetworks.includes(network.name),
...
```

L'optional chaining ne semble pas supporté (malgré le fait que vue3 est censé le faire).
Essayer d'installer un plugin "@babel/plugin-proposal-optional-chaining" n'y change rien.

Avez vous déjà eu des échos de problèmes similaires ? Quelle config utilisez vous exactement ?

**Comment by gideruette** [comment]
Bonjour,

Nous avons eu le même problème. Cela vient de la version de Webpack de Vue3 et de sa configuration par vue-cli.

Le problème a été corrigé dans la version Beta (5.0.0-beta.7)

Je vous recommande de télécharger le Vue-cli en version Beta également, afin d'initialiser votre projet dans de bonnes conditions

**Comment by THouriezPEReN** [comment]
J'ai trouvé une parade avec la version vue-cli courante (la 4.5 de mémoire)
Dans package.json
```json
"scripts": {
    ....
    "preinstall": "npx npm-force-resolutions"
  },
"resolutions": {
    "acorn": "8.0.1"
  },
```

**Comment by laruiss** [comment]
Bonjour, il est conseillé d'utiliser [Vite](https://vitejs.dev) plutôt que Vue-CLI, désormais.
