### ISSUE TITLE
[data-rf-theme] Typo dans le selecteur + update DSFR v1.2

### ISSUE THREAD

**Issue by gideruette** [dnum-mi/vue-dsfr#162]
Bonjour,

Il semblerait qu'il y ait une typo dans la classe `data-rf-theme` (=> `data-fr-theme`)

Par ailleurs, d'après la dernière version du DSFR, il faut désormais utiliser l'attribut `data-fr-scheme`

https://gouvfr.atlassian.net/wiki/spaces/DB/pages/579928166/Param+tres+d+affichage+-+Display
![image](https://user-images.githubusercontent.com/15626856/144143158-a52600c8-5259-41f3-ac97-46497de70747.png)

**Comment by plegaud** [comment]
Oui effectivement il y avait une erreur de typo.

Cela dit nous n'avons pas mis l'attribut data-rf-theme en tant que props des composants.

On va voir pour remplacer partout l'attribut data-fr-theme par data-fr-scheme, une petite refacto à prévoir.

**Comment by laruiss** [comment]
En fait, comme dans le CSS, on mettait déjà bien `data-rf-theme`, ça ne pose pas de problème.

Pour la mise à jour vers DSFR 1.2.1, c'est [déjà en cours](https://github.com/dnum-mi/vue-dsfr/tree/feat/implementation-v1.2.1-du-dsfr), et ça va être un peu long.

**Comment by laruiss** [comment]
Correction livrée dans la `beta.35`
