### ISSUE TITLE
DsfrInput - Disabled

### ISSUE THREAD

**Issue by TaylorGit9** [dnum-mi/vue-dsfr#164]
Peut-on prévoir la possibilité de laisser l'input en disabled à l'aide d'une props supplémentaire ?

**Comment by plegaud** [comment]
Oui effectivement il s'agit d'un oubli.
J'ai ajouté la props aujourd'hui, ça sera livré à la prochaine version.

**Comment by laruiss** [comment]
Corrigé dans [beta.33](https://github.com/dnum-mi/vue-dsfr/releases/tag/v1.0.0-beta.33)
