### ISSUE TITLE
DsfrTable - Clic sur une ligne

### ISSUE THREAD

**Issue by TaylorGit9** [dnum-mi/vue-dsfr#166]
La possibilité de cliquer sur une ligne (pour accéder au détail de l'élément sélectionné par exemple) ne semble pas être implémentée.

**Comment by laruiss** [comment]
Bonjour @TaylorGit9 et merci !

J'ai ouvert une discussion #170, je ferme l'issue et en rouvrirai une autre plus précise une fois qu'on se sera entendu
