### ISSUE TITLE
[DsfrInput] Ajout des attributs standards

### ISSUE THREAD

**Issue by gideruette** [dnum-mi/vue-dsfr#182]
Bonjour,

Nous aurions besoin de l'attribut `required` sur la balise `ìnput` ajoutée dans le composant `DsfrInput`. 
Il est probable que certains des autres [attributs standards ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) finissent par nous intéresser. 

En ajoutant `v-bind="$attrs"` sur l'élément input de DsfrInput, on pourrait [récupérer les attributs passés au parent ](https://v3.vuejs.org/guide/component-attrs.html#attribute-inheritance-on-multiple-root-nodes)?

**Comment by laruiss** [comment]
Livré dans la `beta.35`
