### ISSUE TITLE
DsfrInput textArea

### ISSUE THREAD

**Issue by TaylorGit9** [dnum-mi/vue-dsfr#189]
Peut-on faire évoluer le composant de sorte à ce que le champ de saisie du DsfrInput puisse être un textarea ?
A l'aide par exemple d'une prop :textarea="true".

**Comment by laruiss** [comment]
Bonjour, oui, on va s'en occuper très vite, en effet, c'est un oubli important !

**Comment by laruiss** [comment]
Livré dans [`beta.26`](https://github.com/dnum-mi/vue-dsfr/releases/tag/v1.0.0-beta.36)
