### ISSUE TITLE
Feat : [DsfrTableCell] Utiliser des composants basiques dans les cellules des tableaux

### ISSUE THREAD

**Issue by gideruette** [dnum-mi/vue-dsfr#205]
En ajoutant simplement : ` <component
      :is="isComponent"
      v-if="isComponent"
      v-bind="field"
    >{{field.text}}</component>`, cela permettrait d'utiliser des composants html dans les cellules.
    
Exemple : 
```ts
{
    component: "a",
    href: `#/detail/${id}`,
    "aria-label": "Vers le détail",
    target: "_self",
    text: 'Vers détail',
}
```

**Comment by laruiss** [comment]
Je ne comprends pas la différence avec ce qui existe déjà
