### ISSUE TITLE
Mettre à jour le composant Alert (v1.3)

### ISSUE THREAD

**Issue by DaBadBunny** [dnum-mi/vue-dsfr#223]
Retrait de l'attribut role="alert"
Mise à jour des icones (deux des nouvelles n'existent pas sur Remix Icons)

https://gouvfr.atlassian.net/wiki/spaces/DB/pages/736362500/Alertes+-+Alerts

https://github.com/GouvernementFR/dsfr/releases

**Comment by laruiss** [comment]
Livré dans la [beta.40](https://github.com/dnum-mi/vue-dsfr/releases/tag/v1.0.0-beta.40)
