### ISSUE TITLE
[DsfrTabs] Le composant ne s'affiche pas

### ISSUE THREAD

**Issue by gideruette** [dnum-mi/vue-dsfr#237]
Dans une page ayant du contenu, le composant ne s'affiche pas du tout : 

Sans doute à cause de cette propriété css : `overflow: hidden;`  dans la classe `.fr-tabs`

**Comment by laruiss** [comment]
Bonjour, auriez-vous un exemple minimal qui reproduit le bug ?

**Comment by laruiss** [comment]
Je ferme ce ticket car nous avons utilisé DsfrTabs dans plusieurs projets sans rencontré l’anomalie mentionnée.

Rouvrez ce ticket avec plus de précisions si vous continuez de rencontrer l’anomalie.
