### ISSUE TITLE
DsfrBreadcrumb, max-width

### ISSUE THREAD

**Issue by TaylorGit9** [dnum-mi/vue-dsfr#240]
Nous proposons de retirer la propriété css 'max-width: 10rem;' des classes **fr-breadcrumb__link** et **fr-breadcrumb__item** car cela tronque les libellés.
(Cf https://vue-dsfr.netlify.app/?path=/docs/composants-fil-d-ariane-dsfrbreadcrumb--fil-d-ariane)

**Comment by gideruette** [comment]
Afin de coller au mieux avec la spécification du DSFR, il faudrait peut-être plutôt implémenter cette règle : 

Longueur et lisibilité

Afin qu’il reste lisible, évitez que le fil d’Ariane soit trop long et passe sur plusieurs lignes. Si les titres de page de votre site sont longs, nous conseillons de n’afficher que les 4 premiers mots du nom de la page courante et d’indiquer que l’élément est tronqué par l’affichage de “…”

Ou bien il faut laisser la responsabilité de tronquer les libelle au composant parent

**Comment by laruiss** [comment]
Ceci est une discussion à avoir avec le DSFR, car nous prenons le CSS de la bibliothèque officiel désormais.
