### ISSUE TITLE
possible de configurer une auto-complétion ?

### ISSUE THREAD

**Issue by maxbellec** [dnum-mi/vue-dsfr#242]
D'abord, merci pour cette superbe librairie, qui va nous faire gagner un temps fou :fire:.
Est-il possible de configurer une auto-complétion pour VSCode ou autre Webstorm? J'ai l'impression que ces IDEs vont chercher dans le sous-dossier `types`, qui ne contient pas grand chose et en tout cas pas la définition des composants.

Ce que j'ai essayé :
- si j'importe à la main un composant, par exemple `import {DsfrButton} from '@laruiss/vue-dsfr/dist/vue-dsfr.esm'`, l'auto-complétion fonctionnera sur ce composant, là où il est importé, dans Webstorm (pas sur VScode)
- si j'importe dans le plugin `import {DsfrAccordion, DsfrAccordionsGroup, ...} from '@laruiss/vue-dsfr/dist/vue-dsfr.esm'`, seuls les composants explicitement définis avec `defineComponent` sont reconnus et utilisables partout (sans ré-importer), dans Webstorm (pas sur VScode)

Savez-vous comment je pourrais configurer une auto-complétion globale ?

**Comment by laruiss** [comment]
Bonjour @maxbellec et merci pour votre message encourageant.

Nous sommes toujours en bêta et les retours d’utilisateurs de notre bibliothèque sont très importants.

Vos remarques sont très intéressantes et nous allons investiguer et revenir vers vous dès que possible.

À bientôt

**Comment by laruiss** [comment]
@maxbellec Est-ce que vous pourriez me fournir un projet minimal avec vos configurations, s’il vous plaît ?
