### ISSUE TITLE
Error on module import

### ISSUE THREAD

**Issue by leihuayi** [dnum-mi/vue-dsfr#244]
Dans un projet déjà existant en vue3 + vue-router4 où j'ai fait:
1.` npm install @laruiss/vue-dsfr@beta`
2. Rajouté
```
import VueDsfr from '@laruiss/vue-dsfr'            // Import (par défaut) de la bibliothèque
import '@laruiss/vue-dsfr/dist/vue-dsfr-fonts.css' // Import des polices
import '@laruiss/vue-dsfr/dist/vue-dsfr.css'       // Import des styles globaux
``` 
et rajouté app.use(VueDsfr)

j'ai une erreur en ouvrant mon site:
```
./node_modules/@laruiss/vue-dsfr/dist/vue-dsfr.esm.js 954:31
Module parse failed: Unexpected token (954:31)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

**Comment by laruiss** [comment]
Bonjour,

Est-ce que vous utilisez Vite ?

**Comment by beryl-koller** [comment]
Bonjour,
Non, on travaille sur un projet déjà existant qui avait été initié avec vue-cli en Vue2, qu'on a récemment migré en Vue3 pour pouvoir y intégrer le DSfr.
Tout est public sur ce repo : https://github.com/datalab-mi/Basegun/tree/develop (branche develop).

**Comment by beryl-koller** [comment]
@laruiss petite information complémentaire (je continue à chercher !) : le module fonctionne jusqu'à la version 1.0.0-beta.14, puis j'ai cette erreur à partir de la version beta-16 (puisque pas de beta-15 disponible)

**Comment by laruiss** [comment]
C’est fortement déconseillé d’utiliser vue-cli qui utilise webpack.
Essayez de migrer vers Vite.

**Comment by laruiss** [comment]
J’ai créé une PR pour migrer vers Vite https://github.com/datalab-mi/Basegun/pull/28

**Comment by beryl-koller** [comment]
Merci beaucoup @laruiss ! On avait finalement pris cette direction, et tout juste terminé la migration vers Vite en fin de matinée. Je vais comparer avec ta PR pour vérifier si on a rien loupé dans le processus.

**Comment by laruiss** [comment]
Je vous laisse fermer cette issue si tout fonctionne
