### ISSUE TITLE
DsfrButtonGroup

### ISSUE THREAD

**Issue by InesFTL** [dnum-mi/vue-dsfr#311]
La props button qui prend un tableau des props de Button ne semble pas lire la props disabled lorsque celle-ci est défini par une variable. 

Exemple : 
```
buttonsGroup: [
             {
              label:'Bouton 1', 
              disabled: this.disabledButton
             }
               ]
```
Le binding type :disabled n'est pas non plus accepté.

**Comment by laruiss** [comment]
Pourtant, ça fonctionne ici : https://vue-dsfr.netlify.app/?path=/story/composants-boutons-groupe-de-boutons-dsfrbuttongroup--groupe-de-boutons&args=buttons[0].disabled:true

**Comment by InesFTL** [comment]
Si on passe directement le boolean true il le prend en compte mais si je passe par une variable tierce, cela ne semble pas fonctionné. C'est pour cela que dans l'issue j'ai a disabled j'ai assigné une variable et non directement la valeur true.

**Comment by gideruette** [comment]
Votre variable `buttonsGroup` est-elle déclarée en tant que `computed` ou en tant que `data` ?

**Comment by InesFTL** [comment]
En tant que ```data```

**Comment by gideruette** [comment]
Dans ce cas c'est normal, `buttonGRoup` va être initialisé avec la première valeur de `disabledButton`, mais ses modifications suivantes ne l'impacteront pas.

Pour suivre les modifications de `disabledButton`, et pour que l'affichage soit mis à jour, `buttonGroup` doit être déclaré dans en tant que `computed`
