### ISSUE TITLE
DSFR Alert - message hors cadre

### ISSUE THREAD

**Issue by InesFTL** [dnum-mi/vue-dsfr#332]
Le message du composant DSFR Alert semble sortir du cadre lorsque celui-ci est trop long. 
En haut le composant vuejs Alert, en-dessous le composant natif du _system design d'etat_. 
![Capture d’écran 2022-04-15 à 09 48 07](https://user-images.githubusercontent.com/36988046/163542252-54d39572-fce5-437e-a2b2-c5522d1df452.png)

**Comment by laruiss** [comment]
Je veux bien voir le reste du code, parce que je ne constate pas la même chose ici :
[petite alerte avec description longue](https://vue-dsfr.netlify.app/?path=/story/composants-alertes-dsfralert--alerte&args=description:Description+du+message+super+long+super+super+super+super+long;small:true)

**Comment by InesFTL** [comment]
``` 
<div class="fr-container">
    <div class="fr-grid-row fr-grid-row--gutters fr-grid-row--center">
      <div class="fr-col-12 fr-col-sm-11 fr-col-md-8 fr-col-lg-7 fr-col-xl-6">
        <DsfrAlert
          type="info"
          description="Attention aucun logo n'a été rajouté. Attention aucun logo n'a été rajouté."
          small="small"
        />
        <div class="fr-alert fr-alert--info fr-alert--sm">
          <p>Attention aucun logo n'a été rajouté. Attention aucun logo n'a été rajouté.</p>
        </div>
      </div>
    </div>
  </div>
```

**Comment by laruiss** [comment]
Je ne constate pas le problème sur [ce projet tout simple](https://stackblitz.com/edit/vitejs-vite-578svw?file=src%2FApp.vue&terminal=dev)

**Comment by InesFTL** [comment]
Apparemment dans mon code la classe fr-alert--sm a un attribut height fixé à 40px. Le projet est sous la version 43 du DSFR. _A gauche le tien à droite le mien_

![Capture d’écran 2022-04-15 à 19 38 46](https://user-images.githubusercontent.com/36988046/163603005-adaf3d24-efc8-4e1e-a91c-ff0907df6bf2.png)

**Comment by laruiss** [comment]
Il serait donc temps de migrer vers la dernière version de la bibliothèque

**Comment by laruiss** [comment]
Est-ce que l’anomalie est encore présente après mise à jour de la bibliothèque ?
Est-ce que l’on peut fermer ce ticket ?

**Comment by InesFTL** [comment]
Effectivement la mise à jour à régler le problème 👍
