### ISSUE TITLE
css manquant lors du SSR ?

### ISSUE THREAD

**Issue by maxbellec** [dnum-mi/vue-dsfr#360]
En créant un nouveau projet (avec `yarn create vue-dsfr`), en version `1.0.1`, le rendu en SSR manque d'une partie du style :
![Peek 2022-05-02 09-14](https://user-images.githubusercontent.com/7253902/166198116-84fd3590-cce7-4544-b55f-7d2e4298145b.gif)
Le rendu est bon après hydration. En version `1.0.0-beta.37` je n'avais pas ce problème. Comment puis-je corriger ce rendu SSR ?
Merci !

**Comment by laruiss** [comment]
Bonjour,

Merci pour votre ticket. Voudriez-vous bien fais un projet minimal pour reproduire l'anomalie ?

**Comment by laruiss** [comment]
Bonjour, en effet, nos excuses.

C'est toujours le cas avec la dernière version de create-vue-dsfr ?

**Comment by maxbellec** [comment]
Pour information si les cas d'usage vous intéressent, on (avec mon entreprise TelesCoop) développe avec `vue-dsfr` en Nuxt3 un outil dédié aux professionnels de la médiation numérique dans le cadre d'un appel d'offre de l'ANCT. Le code est open-source ici : https://gitlab.com/telescoop-public/mes-outils-inclusion-numerique/frontend
On publie le site à la fois du mois, la version de preprod est ici http://moine.tlscp.fr/ (l'URL n'est pas pertinente)

**Comment by laruiss** [comment]
Bonjour @maxbellec,

J’aurais aimé parler de ce problème que je voudrais régler très prochainement. Je crois que vous n’êtes pas encore sur le Discord, voici une invitation : https://discord.gg/UKtegTK3

**Comment by laruiss** [comment]
Corrigé avec la `v3.0.0`
