### ISSUE TITLE
Ajouter l'attribut `rel` avec la valeur `noreferrer noopener` pour les balises `<a>` qui ont un attribut `target`

### ISSUE THREAD

**Issue by Nanaki** [dnum-mi/vue-dsfr#377]
La présence de l’attribut "rel" avec les valeurs "noopener noreferrer" est très importante pour des raisons
de sécurité. En effet, cela permet d’éviter que la ressource nouvellement chargée dans le navigateur de
l’utilisateur puisse modifier la page présente sur l’onglet initial.

Cela permet donc de lutter contre des techniques de phishing et les attaques de type « Reverse
tabnabbing », qui consistent à réécrire un lien sur une page pour une attaque de phishing.

**Comment by laruiss** [comment]
C’est déjà le cas...
