### ISSUE TITLE
[suggestion] : supprimer le scroll du body quand une modale est ouverte

### ISSUE THREAD

**Issue by maxbellec** [dnum-mi/vue-dsfr#385]
Le fonctionnement en général attendu quand une modale est ouverte est que le scroll de ce qui est derrière soit désactivé.

Le DSFR le [précise d'ailleurs](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/476610770/Modale+-+Modal)
> Lorsqu’une modale est ouverte, la page en arrière plan se fige, il devient alors impossible de scroller le contenu d’arrière plan avant de l’avoir clôturée. 

Par exemple [Bootstrap ajoute la classe `.modal-open`](https://github.com/twbs/bootstrap/pull/6342) au body quand une modale est ouverte, ce qui permet de faire un

```css
body.modal-open{
  overflow: hidden
}
```

et de supprimer le scroll. Est-ce envisageable que `DsfrModal` le fasse également ?

**Comment by laruiss** [comment]
Oui, c’est une très bonne idée. Vous voudrez bien proposer une PR ?
