### ISSUE TITLE
LTS de node

### ISSUE THREAD

**Issue by tlemaireCDAD** [dnum-mi/vue-dsfr#407]
Bonjour. J'aimerai utilisé vue-dsfr mais il fonctionne avec une version supérieure à la LTS au contraire du DSFR d'origine. Peut -on avoir une version avec node en LTS pour pouvoir l'utiliser?

Cordialement

**Comment by laruiss** [comment]
Je pense que la bibliothèque fonctionne même avec la Node.js 14.

La version indiquée dans le `package.json` est là pour indiquer la version à avoir pour travailler sur la bibliothèque.

D’autre part, la v18 passera en LTS dans quelques semaines.
