### ISSUE TITLE
La version dans le package.json de la source est 1.0.0

### ISSUE THREAD

**Issue by LVerneyPEReN** [dnum-mi/vue-dsfr#408]
La version du dépôt dans le package.json est bloquée à 1.0.0 https://github.com/dnum-mi/vue-dsfr/blob/main/package.json#L3 tandis que la 1.5.0 est publiée.

Est-ce attendu ?

**Comment by laruiss** [comment]
Bonjour,
Oui, ce n’est pas très important. Ce qui est important, c’est le numéro de version dans le `package.json` du package publié.

Cf. https://semantic-release.gitbook.io/semantic-release/support/faq

**Comment by LVerneyPEReN** [comment]
> Oui, ce n’est pas très important.

Dans le cas général, ce n'est pas très important.

Par contre, quand on rebuilde le paquet pour l'uploader localement sur un dépôt privé, ce n'est plus compatible avec le create-vue-dsfr puisque la version publiée n'est pas la bonne :/

**Comment by laruiss** [comment]
Et... 

- pourquoi le mettre sur un dépôt privé ?
- quand bien même, pourquoi le rebuilder et ne pas prendre le paquet déjà buildé ?

**Comment by LVerneyPEReN** [comment]
1/ Il existe des _setups_ dans lesquels l'accès au dépôt public NPM n'est pas possible, et on ne peut alors s'appuyer que sur un dépôt privé.

2/ En cas de modification de vue-dsfr, il est plus pratique de travailler sur son fork buildé localement / pushé sur son dépôt privé et de soumettre les PRs pour validation que de tout bloquer en attendant de revue de PR + publication d'une nouvelle version.

**Comment by laruiss** [comment]
D’accord. Ce sera donc un nouveau package, qui suivra sa propre logique de versionnement.
