### ISSUE TITLE
v1.5.0 et gestion des icones

### ISSUE THREAD

**Issue by maxbellec** [dnum-mi/vue-dsfr#409]
J'ai mis à jour `vue-dsfr` en `1.5.0` depuis la `1.0.0` en même temps qu'un bump de `Nuxt3`. La gestion des icones a-t-elle changée ? La [documentation](https://vue-dsfr.netlify.app/?path=/docs/fondamentaux-4-1-ic%C3%B4nes-personnalis%C3%A9es--page) n'a pas changée, donc j'ai toujours mon plugin dans lequel je 

```
export default defineNuxtPlugin((nuxtApp) => {
  // @ts-ignore
  nuxtApp.vueApp.use(VueDsfr, { icons })
  return
})
```

`icons` étant une liste d'icones importées principalement depuis `oh-vue-icons/icons`.

Avant ça fonctionnait très bien ainsi.
Maintenant les icones sont recherchées comme des fichiers statiques (erreur 404 `http://localhost:3000/icons/system/arrow-right-s-line.svg`)

**Comment by maxbellec** [comment]
Ça fonctionne donc en mettant les icônes dans mon dossier `public`, ça fonctionne. Si c'est ça qu'il faut faire, la documentation mériterait d'être mise à jour. Je garde l'issue ouverte pour ça, mais comme ça fonctionne chez moi, pas de soucis pour que vous fermiez l'issue.

**Comment by laruiss** [comment]
Oh, merci beaucoup ! Je n’ai pas eu le temps de m’en occuper, et apparemment, l´équipe au ministère non plus.

Je regarde ça ce week-end.

**Comment by laruiss** [comment]
> J'ai mis à jour vue-dsfr en 1.5.0 depuis la 1.0.0 en même temps qu'un bump de Nuxt3. La gestion des icones a-t-elle changée ? La [documentation](https://vue-dsfr.netlify.app/?path=/docs/fondamentaux-4-1-ic%C3%B4nes-personnalis%C3%A9es--page) n'a pas changée, donc j'ai toujours mon plugin dans lequel je

Oui, la version 1.5.0 utilise la nouvelle version du DSFR qui a modifié la gestion des icônes, et ça bug. Nous n’avons pas communiqué dessus.

**Comment by DaBadBunny** [comment]
On est sur le coup, une nouvelle version va sortir sous peu qui je l'espère solutionnera cette histoire d'icônes, merci pour le retour
