### ISSUE TITLE
[DsfrSideMenu] Menu is not collapsable in mobile

### ISSUE THREAD

**Issue by ambroisemaupate** [dnum-mi/vue-dsfr#429]
In Documentation, `DsfrSideMenu` is automatically collapsable when using mobile responsive:

https://vue-dsfr.netlify.app/?path=/docs/composants-menu-lat%C3%A9ral-1-menu-entier-dsfrsidemenu--menu-lateral

---

How can I reproduce this behaviour, `toggle-expand` is never emitted when clicking on menu main button:

![image](https://user-images.githubusercontent.com/380026/207681684-e21a4f0e-f5e0-4d82-b8bd-79fee0f38a44.png)

```vue
 <div class="fr-container">
    <div class="admin-menu">
        <DsfrSideMenu
            id="admin-side-menu"
            :heading-title="t('admin.menu.title')"
            :button-label="t('admin.menu.button')"
            :menu-items="menuItems"
            @toggle-expand="toggleExpand"
        />
    </div>
    <div class="admin-content">
        <slot />
    </div>
</div>
```

I noticed a small difference between Storybook and my environment rendered HTML.

Main button has `data-fr-js-collapse-button` attribute and an event attached.
![image](https://user-images.githubusercontent.com/380026/207682632-7ca2699e-00f7-42f9-b7c2-d25b69afd2a0.png)
 
This is not the same in local environment:

![image](https://user-images.githubusercontent.com/380026/207682948-ab93c093-0ba1-47f9-a3e4-abac8b3cc715.png)

Am i missing a configuration step?

**Comment by laruiss** [comment]
On peut peut-être rester en français vue que cette bibliothèque ne sera, je pense, utilisée que par des français pour les français... (Même si je serais honoré qu’elle soit utilisée par de nombreux développeurs de tout plein de pays 😊 )

Pour répondre à votre question, est-ce que les objets de votre tableau `menuItems` contiennent bien une propriété `id` ?

**Comment by ambroisemaupate** [comment]
![image](https://user-images.githubusercontent.com/380026/208264195-987a939d-8244-4dd2-8ade-21b76f1bad6d.png)

Restons en français alors :smile: 

Oui, j'ai essayé avec et sans `id`.

En regardant le code source du composant et de la story je n'arrive pas à comprendre ce qui manque. Y'a t-il une lib JS à charger en plus du plugin Vue ?

**Comment by ambroisemaupate** [comment]
OK 

il manquait un import dans `plugins/vue-dsfr.js`

```js
import '@gouvfr/dsfr/dist/core/core.module.js'
```

Je pense qu'il faudrait mettre à jour la documentation pour Nuxt 3 : http://localhost:6006/?path=/story/docs-2-guide-d-utilisation--page

**Comment by laruiss** [comment]
Je préfère ne pas importer le JS du DSFR. Ça fait des bundles trop gros alors que tout devrait déjà être dans la bibliothèque.
Je regarde ce problème et trouve une autre solution.
