### ISSUE TITLE
[Storybook][Suggestion] Uniformiser les noms des rubriques avec le noms du composant

### ISSUE THREAD

**Issue by ambroisemaupate** [dnum-mi/vue-dsfr#452]
Il s'agit d'une suggestion pour améliorer la lisibilité du Storybook.
Je passe pas mal de temps à chercher mes composants dans le menu de Storybook car il ne sont pas trié par nom technique mais par leur traduction FR:

![image](https://user-images.githubusercontent.com/380026/213148899-2c491ca6-2a0e-4b1e-997d-952163c1390e.png)

La navigation serait simplifiée si on parcourait par nom du composant Vue. On pourrait s'inspirer du portage React du DSFR qui un storybook au petits oignons : https://react-dsfr-components.etalab.studio/?path=/docs/components-input--default

![image](https://user-images.githubusercontent.com/380026/213149217-efaf1fb7-11df-48b2-b538-dd84af7c4816.png)

**Comment by laruiss** [comment]
Je ne suis pas contre, cependant, le champ de recherche est fait pour ça, il me semble 😊 

Les composants sont dans le même ordre que sur la [doc officielle](https://www.systeme-de-design.gouv.fr/elements-d-interface)
