### ISSUE TITLE
Lien stackblitz 

### ISSUE THREAD

**Issue by scenaristeur** [dnum-mi/vue-dsfr#464]
Bonjour, le lien vers stackblitz dans le paragraphe 'Dans nuxt3' de la page https://vue-dsfr.netlify.app/?path=/story/docs-2-guide-d-utilisation--page ne fonctionne pas.

**Comment by laruiss** [comment]
Ah, je vais regarder ça aujourd'hui

**Comment by laruiss** [comment]
Ce sera sur codesandbox désormais.

https://codesandbox.io/p/github/laruiss/nuxt-dsfr/nuxt-dsfr

C’est une copie du dépôt GitHub https://github.com/laruiss/nuxt-dsfr

Je corrige la doc très vite

**Comment by laruiss** [comment]
Corrigé
