### ISSUE TITLE
[DsfrHeader] Ajouter un slot pour un DsfrNavigation

### ISSUE THREAD

**Issue by cailliaud** [dnum-mi/vue-dsfr#499]
# TL;DR;
Ajouter à l'existant [DsfrHeader](https://github.com/dnum-mi/vue-dsfr/blob/main/src/components/DsfrHeader/DsfrHeader.vue) la possibilité d'avoir un slot pour un [DsfrNavigation](https://github.com/dnum-mi/vue-dsfr/blob/main/src/components/DsfrNavigation/DsfrNavigation.vue).

# Détails

Dans le cadre d'un projet pour le Ministère de l'Intérieur et des Outre-Mer, nous avons besoin que le DsfrNavigation soit intégré au DsfrHeader.

Exemple de rendu souhaité:
![image](https://user-images.githubusercontent.com/19285360/221866903-e71788b4-b449-4c93-96ad-f41127fa112a.png)

Actuellement, il n'est pas possible d'avoir un DsfrNavigation au sein du DsfrHeader. Il doit donc être positionné à la suite ce qui donne un rendu bien différent:
![image](https://user-images.githubusercontent.com/19285360/221867743-1861d006-c385-4504-9ebd-9678222a65ce.png)

Pour le moment, nous sommes parti sur une vision custom du DsfrHeader où on ajoute dans le DsfrHeader notre DsfrNavigation. Ce slot pourrait intéresser d'autres équipes / projets.

**Comment by cailliaud** [comment]
Merci @ShallowRed  pour le tips concernant [Teleport](https://vuejs.org/guide/built-ins/teleport.html#teleport). C'est un composant que je n'ai pas eu l'occasion d'utiliser encore ^^ Une bien belle découverte

**Comment by ShallowRed** [comment]
Je dis ça mais je suis au tout début d'´un projet... J'ai l'impression que l'emplacement où "téléporter" le menu de nav n'est pas le même en mobile et en dekstop

Les sélecteurs suivant semblent donner un rendu satisfaisant :
 - Mobile : 'header #header-navigation>div'
 - Desktop : 'header>div>div.fr-container'
