### ISSUE TITLE
:bug: `DsfrHeaderMenuLinks` onClick sur quickLink n'est plus pris en compte

### ISSUE THREAD

**Issue by clairenollet** [dnum-mi/vue-dsfr#511]
# Reproduire le bug

- un `DsfrHeader` ou un `DsfrHeaderMenuLinks` avec une props `quickLinks` contenant un `quickLink` (`mail.to`)

```js
const openMailEditor = () => {
  window.location = 'mailto:blabla@test.gouv.fr'
}

const quickLinks = ref([
  {
    label: 'Contactez-nous',
    title: mail.address,
    path: '/',
    onClick: () => openMailEditor(),
    icon: 'ri-mail-line',
  },
])
```

Le clic sur le bouton ne déclenche plus le `onClick`.

## Contexte

Bug introduit en `3.0.0` (pas de problème en `2.1.1`), sans doute ce commit : https://github.com/dnum-mi/vue-dsfr/commit/af6758d84340a77b400aa1074bf75329cb229833

**Comment by NadeigeC** [comment]
C'est fix avec `3.2.0` @clairenollet, j'avais ce problème également et ça concernait tous les quickLinks

**Comment by clairenollet** [comment]
> C'est fix avec `3.2.0` @clairenollet, j'avais ce problème également et ça concernait tous les quickLinks.

Merci Nadeige,
pas sûre qu'il s'agisse du même bug, je suis bien en `3.2.0` !
La redirection vers le `to`, `path` ou `href` spécifié fonctionne bien, c'est vraiment le `onClick` qui ne fonctionne plus. Sachant que mon `quickLink` est en fait un bouton de contact qui déclenche via la fonction passée à `onClick` une "redirection" vers `mailto` (ça provoque l'ouverture de la messagerie configurée s'il y en a une).
Ou alors ce n'est pas un bug mais du coup ce serait bien de pouvoir passer un lien `mailto` à un `quickLink` !
