### ISSUE TITLE
[DsfrInput] Empêcher la saisie des dates invalides

### ISSUE THREAD

**Issue by cailliaud** [dnum-mi/vue-dsfr#545]
# TL;DR;
Le [DsfrInput](https://github.com/dnum-mi/vue-dsfr/blob/main/src/components/DsfrInput/DsfrInput.vue) permet la saisie de date invalide et va laisser la date invalide affichée malgré un modelValue avec une valuer `""`

# Reproduction

Ajouter un champs DsfrInput de type date dans un formulaire, vous pourrez-alors saisir la valeur suivante par exemple:
![image](https://github.com/dnum-mi/vue-dsfr/assets/19285360/97d5c586-8192-48f9-9e15-9fb225b8df2e)
Ici, la date saisie est le 31/06/2023 qui n'est pas un jour valide

Si on check l'état du composant, on peut voir qu'il a le model value à `""`
![image](https://github.com/dnum-mi/vue-dsfr/assets/19285360/e434b41c-b894-43ef-b018-2a9ce02b8e6b)

# Détails
Nous avons étudié de notre côté si nous pouvions gérer ce contrôle mais malheureusement il faut être au plus prêt de l'input html.

Les champs `<input type="date"/>` font déjà de la validation, et remontent une valeur vide `""` à vue. À noter que lorsque le champ n’est PAS rempli, la valeur est vide aussi, donc on ne peut pas différencier les 2.

Une bonne piste: on a accès à <elementHtml>.value.$el.getElementsByTagName('input')[0].validity qui nous retourne les validateurs définis par la specs, et les valeurs calculées par le user-agent. (Voir [ValidityState - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState) )

**Comment by laruiss** [comment]
Bonjour et merci pour ce ticket détaillé !
Je viens de passer ces dernières semaines à tout migrer vers script setup et TS. Je vais pouvoir regarder cela prochainement.

Cependant, je vous invite à créer une PR si vous avez la solution 😊

**Comment by laruiss** [comment]
Les nouveaux types de HTML5 de la balise `<input>` ont un comportement particulier :
- la valeur n’est disponible que lorsqu’elle est valide (pas d’événement DOM input si elle n’est pas valide)
- si la valeur redevient invalide, l’événement DOM renvoie la chaîne vide, puis ne déclenche plus d’événement tant que la valeur n’est pas valide. Vue ne peut rien faire, c’est le navigateur qui lui renvoie la valeur

**Comment by cailliaud** [comment]
Merci pour l'investigation.
Je vois pas comment on va faire côté frontend pour gérer ce cas sans aucun évènement du DOM ^^'
Heureusement, le backend a sa validation au cas où
