### ISSUE TITLE
`DsfrBreadcrumb` - Problème de type de la propriété `links`

### ISSUE THREAD

**Issue by mlbiche** [dnum-mi/vue-dsfr#546]
Si j'en crois la documentation Storybook, le composant `DsfrBreadcrumb` attend le type `Array<{ text: string, to?: RouteLocationRaw }>` pour la propriété `links`.

Pourtant, si je comprends bien la définition des types, il semblerait que seuls les types suivants soient acceptés (cf. la [définition de types](https://github.com/dnum-mi/vue-dsfr/blob/b3a16b53b85ad0dea63976802176d86da8dc60c6/types/components/DsfrBreadcrumb/DsfrBreadcrumb.vue.d.ts)) :
* `Array<{ text: string }>` (_props_ définies l.6)
* `{ text: string; to: RouteLocationRaw }` (_defaults_ définis l.26)

Lorsque je fournis la variable suivante :

```vue
<template>
  <DsfrBreadcrumb :links="breadcrumbLinks" />
</template>

<script setup lang="ts">
  import { DsfrBreadcrumb } from '@gouvminint/vue-dsfr'

  // RouteTitle.*() and RoutePath.*() are strings
  const breadcrumbLinks: BreadcrumbLinks = [
    { text: RouteTitle.App(), to: RoutePath.App() },
    { text: RouteTitle.Users() }
  ]
</script>
```

TypeScript râle avec l'erreur suivante sur la propriété `links` :

```
Type '{ text: string; to?: string | undefined; }[]' is missing the following properties from type '{ text: string; to: RouteLocationRaw; }': text, to
```

**Comment by laruiss** [comment]
J’ai migré tout le code en script setup et en TS, je pense que ça devrait régler ce problème. Je vous invite à essayer la v4.0.2 et éventuellement à fermer ce ticket si cela corrige le problème.

**Comment by mlbiche** [comment]
C'est parfait, merci pour ce boulot conséquent !!
