### ISSUE TITLE
Où utiliser DsfrSideMenuButton

### ISSUE THREAD

**Issue by Leni-Vienne** [dnum-mi/vue-dsfr#550]
Bonjour,
J'essaye actuellement de faire un menu latéral qui contient des sous-menus et sous-composants, je ne peux donc pas passer par un simple prop "menuItems". En lisant la doc je ne vois pas de code associer à ce composant DsfrSideMenuItems qui semble essentiel pour déplier les sous-menus et je m'y perds un peu. Quelqu'un pourrait-il partager du code d'un sideMenu avec l'arborescence/hiérarchie entre SideMenu, SideMenuList, SideMenuItemList, etc.?

Aussi j'avais le souvenir d'une ancienne documentation qui contenait des gros morceaux de code TS (je crois), est-elle toujours en ligne ?

Merci d'avance et merci à tous ceux qui contribuent à cet outil :)

**Comment by laruiss** [comment]
Bonjour @Leni-Vienne et merci pour vos encouragements !

Effectivement, le code montré sur Storybook est moins complet depuis la version 7, il faudra que je regarde ça.

En attendant, je vous invite à regarder le code utilisé dans les stories, par exemple ici : https://github.com/dnum-mi/vue-dsfr/blob/main/src/components/DsfrSideMenu/DsfrSideMenu.stories.ts

**Comment by Leni-Vienne** [comment]
Merci beaucoup ça change tout ! Donc un side menu ne peut pas être construit avec des sous-composants, des balises html ? uniquement avec l'objet menuItems ?

**Comment by laruiss** [comment]
Un side menu doit effectivement respecter normalement le [DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/menu-lateral)
