### ISSUE TITLE
classes CSS 'fr-input--error' et 'fr-input--valid' manquantes

### ISSUE THREAD

**Issue by Leni-Vienne** [dnum-mi/vue-dsfr#567]
Bonjour,
J'essaye de faire un champ texte qui devient vert après validation (sans afficher de message de validation) mais le prop `is-valid` (ou isValid) du composant DsfrButton ne fonctionne pas. En revanche, le prop `valid-message` de DsfrInputGroup semble servir de condition, mais a l'inconvénient d'afficher `true` en dessous du champ puisqu'il n'est pas fait pour cela à la base
![image](https://github.com/dnum-mi/vue-dsfr/assets/71212417/33d4a6af-03d6-4cfc-8644-753acd25f07e)

En regardant le code du composant DsfrButton, je vois qu'il fait appel à la classe CSS 'fr-input--valid' or elle n'a pas l'air d'exister (tout comme 'fr-input--error') quand je l'appelle seule.
https://github.com/dnum-mi/vue-dsfr/blob/main/src/components/DsfrInput/DsfrInput.vue
Résultat aucun de ces deux exemples simplifiés ne fonctionne :
```
<div class="fr-input-group">
    <input class='fr-input--valid'>
</div>
<DsfrInputGroup>
    <DsfrInput v-model="test" :is-valid="true" />
</DsfrInputGroup>
```
Quelqu'un peut-il confirmer le problème ? il est possible que ça vienne de moi, je suis loin de maîtriser Dsfr. Merci :)

**Comment by laruiss** [comment]
Il faut utiliser `valid-message` et `error-message` comme ceci :

```
  <DsfrInputGroup
    v-model="test"
    :valid-message="validMessage"
    :error-message="errorMessage"
  />
  ```
  les bonnes classes seront ajoutées sur les bons éléments si `validMessage` ou `errorMessage` est défini et n’est pas une chaîne vide.
  
  J’ai ajouté un lien vers le serveur discord dans la documentation. Je vous invite à y poser ce genre de questions.

**Comment by Leni-Vienne** [comment]
Merci, le lien Discord pourra s'avérer utile. Mais je ne comprend pas trop votre code. D'une part avec le v-model dans le composant InputGroup la valeur n'est pas pas "bind" sur l'input en lui même (le champ est vide) et un InputGroup n'est-il pas censé pouvoir contenir plusieurs Input ?
Aussi mon problème est que le valid-message s'affiche dès qu'il est non-vide, et que le prop :is-valid ne sert à rien.
Voilà mon code exact à l'intérieur d'un v-for, qui a pour moi toute les raisons de fonctionner
```
<DsfrInputGroup valid-message="modifié">
    <DsfrInput :placeholder="item.valeur" v-model="item.valeur"
        :is-valid="dernierModifie === item.id_var" />
</DsfrInputGroup>
```
