### ISSUE TITLE
Erreur avec webpack :  not found: Error: Default condition should be last one

### ISSUE THREAD

**Issue by ajacque-trydea** [dnum-mi/vue-dsfr#573]
Bonjour, 
Depuis la release 4.0.1, il est impossible d'utiliser le package dans une application construite par webpack.

A la compilation, l'erreur suivante est lancée : 
Module not found: Error: Default condition should be last one

Après quelques recherches, il semble que dans la partie "exports" de package.json, "default" devrait être le dernier élément de la liste. Or dans les fichiers de release, "types" intervient après "default"

refs : 
[doc webpack](https://webpack.js.org/guides/package-exports/#conditional-syntax)
[doc node](https://nodejs.org/api/packages.html#conditional-exports)

### Comment reproduire le bug : 

initialiser un projet node avec le fichier package.json suivant : 

``` json
{
  "name": "untitled",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^5.88.1",
    "webpack-cli": "^5.1.4"
  },
  "dependencies": {
    "@gouvminint/vue-dsfr": "^4.1.0"
  }
}

```

créer un fichier src/index.js avec le contenu suivant : 

``` js
import VueDsfr from '@gouvminint/vue-dsfr'
```

executer `npm run build`

### Contournement du problème : 

Utiliser la version 4.0.0 du package vue-dsfr

modifier le package.json du package dans node module pour placer les "export.default" en dernière position (non reecommandé, uniquement pour devs)

**Comment by laruiss** [comment]
Bonjour, merci, je vais regarder ça très bientôt.

Par curiosité, pourquoi utilisez-vous encore webpack ?

**Comment by ajacque-trydea** [comment]
Merci d'avance,

Le projet tourne sur une base de php74 + symfony et la gestion des assets est plus simple avec webpack (bien que sa configuration soit un calvaire). De plus il s'agit d'un projet historiquement sous webpack. Donc peu de possibilité de changements

**Comment by laruiss** [comment]
@ajacque-trydea Bonjour, voudrez-vous bien confirmer que c’est corrigé dans la [v4.0.2](https://github.com/dnum-mi/vue-dsfr/releases/tag/v4.2.1) ?

**Comment by ajacque-trydea** [comment]
Je confirme que tout fonctionne normalement, merci pour la reactivité !
