### ISSUE TITLE
[DsfrSearchBar] prop label-visible non fonctionnel

### ISSUE THREAD

**Issue by ajacque-trydea** [dnum-mi/vue-dsfr#597]
Le composant searchBar déclare une prop "label-visible" mais modifier celle-ci ne change rien au composant

possible fix : 
``` html
<DsfrInput
      :id="id"
      type="search"
      :placeholder="placeholder"
      :model-value="modelValue"
      :label-visible="false" <!-- ------ :label-visible="label-visible" ------- --> 
      :label="label"
      :disabled="disabled"
      @update:model-value="$emit('update:modelValue', $event)"
      @keydown.enter="$emit('search')"
    />
```

**Comment by laruiss** [comment]
J’ai plutôt l’impression que ça fonctionne très bien.
Regardez un exemple ici :

https://dsfr-input-label.netlify.app/

(un lien vers le code source est sur la page)

Si vous avez réellement écrit `:label-visible="label-visible"`, vous risquez effectivement d’avoir des résultats assez aléatoires.
Attendu que ce qu’il y a à l’intérieur des guillemets (`label-visible`) est une expression qui sera évaluée (puisque le nom de la prop est précédé du caractère `:`), le composant `DsfrInput` recevra un `Number` qui sera le résultat de la soustraction `label - visible`... Vraisemblablement toujours `NaN`, et donc ce sera évalué à `false` puisque la prop attend un booléen.

Si le problème persiste, merci de refaire un projet à partir de ce [gabarit](https://github.com/laruiss/vue-dsfr-repro-template) et de rouvrir l’issue avec un lien vers ce projet.

**Comment by ajacque-trydea** [comment]
Je n'ai pas été assez clair dans mon ticket, désolé.
Ce n'est pas le dsfr Input qui pose problème mais le dsfr search bar.
et l'extrait de code fourni présente un correctif à appliquer au fichier DsfrSearchBar.vue afin de corriger le problème.

**Comment by laruiss** [comment]
D’accord, mes excuses, je vais regarder ça !
