### ISSUE TITLE
[DsfrTable] Contenu dynamique/réactif pas pris en compte

### ISSUE THREAD

**Issue by alemangui** [dnum-mi/vue-dsfr#599]
Le composant _DsfrTable_ semble marcher seulement pour du contenu statique ou inchangeable. 

Par exemple, si je crée une petite table avec des données statiques des mascottes tout va bien:
```vue
<DsfrTable
  title="Pets"
  :headers="['Name', 'Kind']"
  :rows="[
    ['Snoopy', 'Dog'],
    ['Nemo', 'Fish'],
    ['Tigger', 'Cat'],
  ]"
/>
```

![image](https://github.com/dnum-mi/vue-dsfr/assets/1225929/29f9cedd-e448-49a9-b19e-58300c0b8cb3)

Par contre, si ce contenu était téléchargé via une API, rien n'est affiché. Par exemple, si je simule un call API de deux seconds :

```vue
<DsfrTable title="Pets" :headers="['Name', 'Kind']" :rows="pets" />
...
<script>
export default {
    data() {
        return { pets: [] }
    }
    mounted() {
        const self = this
        setTimeout(() => {
          self.pets = [
            ["Snoopy", "Dog"],
            ["Nemo", "Fish"],
            ["Tigger", "Cat"],
          ]
        }, 2000)
  },
}
```
![image](https://github.com/dnum-mi/vue-dsfr/assets/1225929/4705c966-c412-4826-ac16-9b7b39dea755)

Malgré le fait que `pets` contienne bien le tableau attendu.
![image](https://github.com/dnum-mi/vue-dsfr/assets/1225929/d4fe11d5-4976-4d6d-bba7-3b95ec433b8d)

**Comment by laruiss** [comment]
Cela semble fonctionner normalement :

Regarder [cet exemple](https://dsfr-table-async.netlify.app)

**Comment by hfroot** [comment]
C'est bizarre, parce que quand je crée un projet avec `npm init vue-dsfr` je vois comment la liste est mise à jour mais non pas le `DsfrTable`
https://main--profound-rabanadas-bd123d.netlify.app/
https://github.com/hfroot/vue-dsfr-table

Mais quand je remplace tout le code du fichier App.vue dans votre repo @laruiss avec le suivant ça marche bien. C'est difficile d'identifier les changements que vous avez fait dès le `npm init ...` depuis l'historique de commits. Est-ce qu'il y a quelque chose de plus qu'on a besoin de faire ? https://github.com/hfroot/vue-dsfr-table/commits/main
```
<template>
  <div>
    <h1>Test DSFR table refresh</h1>
    <DsfrTable :headers="headers" :rows="pets" />
    <ul>
      <li v-for="pet in pets" :key="pet[0]">{{ pet[0] }}</li>
    </ul>
  </div>
</template>

<script>
export default {
  data() {
    return {
      headers: ["H1", "H2"],
      pets: [["test", "example"]],
    }
  },
  mounted() {
    this.pets = [["new entry", "stuff"]]
  },
}
```
