### ISSUE TITLE
[DsfrSelect] type de la valeur sélectionnée

### ISSUE THREAD

**Issue by ajacque-trydea** [dnum-mi/vue-dsfr#604]
### Problème rencontré : 
Le type du v-model est string | number.  cependant, en mettant un tableau de nombre dans la prop 'options', le model est transformé en string.

### Comportement attendu : 
Que le model soit du type de ce qui est passé dans le tableau d'options

### Solution possible : 
Le fait de passer les éléments de 'options' dans l'attribut value de l'élément <option> transforme la valeur en string. Il serait possible de ne plus passer la valeur de l'élément du tableau 'options' dans l'attribut value mais plutot sa place dans le tableau. ça permettrait par ailleurs de de passer le v-model en type 'any' et options en le type ci-dessous : 
```ts 
(string | number | {
        value: any;
        text: string;
        disabled: boolean;
    })[];
```

**Comment by laruiss** [comment]
DsfrSelect n’est qu’un élément html natif `<select>` habillé.
Or un élément `<select>` ne peut avoir pour valeurs que des `string`s, les gestionnaires d’événement DOM ne peuvent donc renvoyer que des `string`.
*VueDsfr* n’y peut rien, *Vue* n’y peut rien, et *TypeScript* y peut encore moins...
Charge au développeur de faire les conversions qu’il faut là où il faut.

**Comment by ajacque-trydea** [comment]
Je comprends le point de vue mais dans ce cas, le type number ne devrait pas être présent dans les types du v-model si le choix est de garder le fonctionnement du `select` natif

**Comment by laruiss** [comment]
Je vais regarder les types
