### ISSUE TITLE
Évolution du composant DsfrTile

### ISSUE THREAD

**Issue by ShallowRed** [dnum-mi/vue-dsfr#611]
La release 4.7 du vue-dsfr implémente les évolutions du composant DsfrTile dans le dsfr 1.10. ([78e8025](https://github.com/dnum-mi/vue-dsfr/commit/78e80250da17d8cf9a58082bfaac62be5fdb4dd9))

J'avais proposé une [implémentation similaire](https://github.com/dnum-mi/vue-dsfr/pull/603), il me semble qu'au moins deux de ses caractéristiques doivent être implémentées :
- ajout de l'attribut 'download' au lien de la tuile quand la prop correspondante est vraie
- ne pas appliquer la classe  'fr-tile--no-icon' à la tuile en l'absence de la prop ImgSrc qui n'est pas liée

**Comment by DaBadBunny** [comment]
J'avais approuvé ta PR pourquoi l'avoir fermée ?

**Comment by ShallowRed** [comment]
Mince c'est en supprimant mon fork que ça à clôturé la PR.
Désolé je manque vraiment de maitrise de git.
