### ISSUE TITLE
DsfrFooter slot #description : [Vue warn]: Hydration children mismatch

### ISSUE THREAD

**Issue by ChrisD92** [dnum-mi/vue-dsfr#620]
Bonjour,

je rencontre ces warning lorsque j'utilise le composant DsfrFooter avec le slot #description : 

[Vue warn]: Hydration children mismatch in <p>: server rendered element contains fewer child nodes than client vdom. 
  at <DsfrFooter a11y-compliance="non conforme" before-mandatory-links= 
Array [ {…} ]
 logo-text= 
Array(3) [ "Ministère", "de l’intérieur", "et des outre-mer" ]
  ... > 
  at <FooterSection> 
  at <Default ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= 
Object { ref: {…} }
 name="default" > 
  at <NuxtLayoutProvider layoutProps= 
Object { ref: {…} }
 key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot> [deps:1449:13](http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/)
[Vue warn]: Hydration node mismatch:
- Client vnode: ul 
- Server rendered DOM: 
<div> <empty string> 
  at <DsfrFooter a11y-compliance="non conforme" before-mandatory-links= 
Array [ {…} ]
 logo-text= 
Array(3) [ "Ministère", "de l’intérieur", "et des outre-mer" ]
  ... > 
  at <FooterSection> 
  at <Default ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= 
Object { ref: {…} }
 name="default" > 
  at <NuxtLayoutProvider layoutProps= 
Object { ref: {…} }
 key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot> [deps:1449:13](http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/)
[Vue warn]: Hydration children mismatch in <div>: server rendered element contains more child nodes than client vdom. 
  at <DsfrFooter a11y-compliance="non conforme" before-mandatory-links= 
Array [ {…} ]
 logo-text= 
Array(3) [ "Ministère", "de l’intérieur", "et des outre-mer" ]
  ... > 
  at <FooterSection> 
  at <Default ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= 
Object { ref: {…} }
 name="default" > 
  at <NuxtLayoutProvider layoutProps= 
Object { ref: {…} }
 key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>

Je suis sur Nuxt 3 et j'utilise la librairie sous forme de plugin. Le problème est le même avec les éléments de l'exemple : https://github.com/dnum-mi/vue-dsfr/blob/main/src/components/DsfrFooter/DsfrFooter.stories.ts

De plus le chargement est assez long depuis l'ajout de ce composant. 
Avez-vous une idée pour régler ça ?

**Comment by laruiss** [comment]
Si les Id de certains éléments ne sont pas donnés, ils sont générés aléatoirement, et donc une fois côté serveur et une fois côté client, et donc il y a un mismatch.

Veuillez donner plus de détail si même en donnant des valeurs pour les attributs `id` pour les éléments pour lesquels c’est important vous rencontrez toujours le problème.
