### ISSUE TITLE
Bloc non-nécessaire dans le composant `DsfrCallout`

### ISSUE THREAD

**Issue by mlbiche** [dnum-mi/vue-dsfr#629]
Bonjour,

Quand on utilise le composant `DsfrCallout`, il y a un bloc qui n'apparaît pas dans la documentation du DSFR mais qui est pourtant présent dans le DOM. Cet élément n'impacte pas l'affichage.

```html
<div class="fr-mt-n2w  fr-mb-2w  fr-ml-n4w"></div>
```

Il est explicitement défini dans le code du composant : https://github.com/dnum-mi/vue-dsfr/blob/main/src/components/DsfrCallout/DsfrCallout.vue#L20

A-t-il une utilité particulière ? Sinon, peut-il être retiré (je peux ouvrir une PR pour ça) ?

Merci

**Comment by DaBadBunny** [comment]
Ca vient d'être mergé ! Merci pour ton retour.
