### ISSUE TITLE
DsfrSkipLinks - Story non disponible actuellement

### ISSUE THREAD

**Issue by AzuriDigital** [dnum-mi/vue-dsfr#644]
Bonjour,

Actuellement la story du composant DsfrSkipLink https://vue-dsfr.netlify.app/?path=/story/composants-dsfrskiplinks--liens-d-evitement
n'est pas disponible.

Cordialement

**Comment by cailliaud** [comment]
ça tombe bien car @abraccoippon propose une PR pour améliore le DsfrSkipLinks et réparer la story 
https://github.com/dnum-mi/vue-dsfr/pull/642

**Comment by cailliaud** [comment]
Ca semble bien fonctionner avec la release 5.2.0

https://vue-dsfr.netlify.app/?path=/story/composants-dsfrskiplinks--liens-d-evitement
![image](https://github.com/dnum-mi/vue-dsfr/assets/19285360/acd390f2-a4eb-4a3a-8918-ed49810c6446)

**Comment by AzuriDigital** [comment]
Super c'est fonctionnel, merci!
