### ISSUE TITLE
Faire les modifications nécessaires pour la version 1.11 de `@gouvfr/dsfr`

### ISSUE THREAD

**Issue by laruiss** [dnum-mi/vue-dsfr#679]
Partie 1 :

- [x] #680
- [x] #681
- [x] #683

Partie 2
- [x] #685
- [x] #686
- [x] #687

**Comment by laruiss** [comment]
- [ ] https://github.com/GouvernementFR/dsfr/commit/003d5e646a55baebf095ac20c26e5ac361973369

**Comment by vincentlaine** [comment]
@laruiss j'ai sûrement un peu de temps aujourd'hui, tu as besoin d'aide sur quels points ?
Le range j'ai regardé mais je crois qu'il dépend de la librairie JS DSFR, je sais pas comment vous gérez ça au niveau de la librairie Vue

**Comment by laruiss** [comment]
Je ne vois ton message que maintenant... Tu veux pas nous rejoindre sur le serveur Discord ?
Je voudrais éviter d’importer le JS du DSFR. Effectivement, ils font beaucoup de choses dans le JS dans le composant Curseur. J’y ai passé du temps, et j’ai réussi à obtenir le même résultat qu’eux.
