### ISSUE TITLE
DsfrFooter - Condition d'affichage de la licence 

### ISSUE THREAD

**Issue by AzuriDigital** [dnum-mi/vue-dsfr#692]
Bonjour,

Si une licence n'est pas renseigné pour le footer, le paragraphe et le lien sont toujours présents dans l'HTML. Malheureusement le lien vide crée une erreur d'accessibilité. 

Est-il possible d'ajouter une condition d'affichage sur le paragraphe (ex: si licenceText est vide) pour l'afficher ou non ?

**Comment by laruiss** [comment]
Bonjour et merci pour votre ticket. Nous allons regarder cela dès la semaine prochaine.
Auriez-vous une PR à proposer ?

**Comment by laruiss** [comment]
Corrigé dans la [v5.6.2](https://github.com/dnum-mi/vue-dsfr/releases/tag/v5.6.2)
