### ISSUE TITLE
DsfrButton - Gestion des icones DSFR non remix icon

### ISSUE THREAD

**Issue by AzuriDigital** [dnum-mi/vue-dsfr#693]
Bonjour,

Actuellement il ne semble pas possible d'utiliser les icones du DSFR dans le DsfrButton mais uniquement ceux exportés par Remicon.

Est-il possible de prévoir une évolution pour ce cas d'usage ?

Cordialement

**Comment by laruiss** [comment]
Bonjour, oui, c’est déjà sur develop, ce sera dans la prochaine version publiée, j’espère dans quelques jours, ce sera le cas aussi pour DsfrTag, et dans des versions futures pour tous les autres composants qui ont une prop `icon`.

Si la valeur de la prop `icon` est une string et commence par `fr-icon-`, c’est l’icône DSFR qui sera utilisée.

**Comment by laruiss** [comment]
Fait dans la [v5.6.2](https://github.com/dnum-mi/vue-dsfr/releases/tag/v5.6.2)
