### ISSUE TITLE
Rajouter labelPosition (gauche ou droite) et separator sur DsfrToggleSwitch

### ISSUE THREAD

**Issue by Forster-Groux** [dnum-mi/vue-dsfr#728]
=> https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/interrupteur/

Sur la doc du Dsfr il est indiqué la possibilité :
- de choisir la position (gauche ou droite) du label
- d'avoir un séparateur horizontal optionnel sous le component

Ces deux fonctionnalités ne sont pas présentes actuellement sur le DsfrToggleSwitch

**Comment by laruiss** [comment]
Bonjour et merci. Pourriez-vous proposer une PR ?

**Comment by laruiss** [comment]
Présent dans la [v5.9.0](https://github.com/dnum-mi/vue-dsfr/releases/tag/v5.9.0)
