### ISSUE TITLE
DsfrTabs - Les animations d'entrée et sortie ne sont pas les mêmes

### ISSUE THREAD

**Issue by nicolaskempf57** [dnum-mi/vue-dsfr#729]
Les [DsfrTabContent](https://github.com/dnum-mi/vue-dsfr/blob/main/src/components/DsfrTabs/DsfrTabContent.vue#L45) ont une animation différente entre `enter` et `leave`.

Ce code semble provenir de l'exemple de la [documentation vue](https://vuejs.org/guide/built-ins/transition#css-transitions).

Dans le cas des onglets, cela pose problème parce que la transition `leave` est plus lente que la transition `enter`. Cela engendre une superposition en fonction de certains contenus.

On s'en rend compte en modifiant le code HTML sur storybook pour avoir un onglet avec une search-bar large et un autre onglet avec une card.

**Comment by laruiss** [comment]
Bonjour, d’accord, nous allons voir cela dès que possible.

**Comment by laruiss** [comment]
Vous voulez bien faire un mini projet qui reproduit le problème ?
