### ISSUE TITLE
DsfrTags - La prop 'selected' des tags est documentée mais pas implémentée

### ISSUE THREAD

**Issue by Jackidu54** [dnum-mi/vue-dsfr#731]
Dans la documentation des étiquettes sélectionnables, la prop 'selected' est mentionnée mais n'est pas implémentée dans le code. 
Pour avoir le visuel sélectionné ou non, il est actuellement nécessaire d'utiliser l'attribut style.

https://vue-dsfr.netlify.app/?path=/story/composants-dsfrtags--etiquettes-selectionnables&args=tags[1]:!undefined

**Comment by laruiss** [comment]
Oui, cette prop ne devrait pas exister : il faut utiliser vous-même l’attribut natif HTML `:aria-pressed="selected"` avec `selected` qui vaudra la chaîne `'true'` ou `'false'`
