### ISSUE TITLE
Possibilité de mettre une route dans les boutons de la page 404

### ISSUE THREAD

**Issue by alemangui** [dnum-mi/vue-dsfr#739]
Aujourd'hui, le composant [page 404](https://vue-dsfr.netlify.app/?path=/story/composants-dsfrerrorpage--page-erreur-404) permet de spécifier un tableau de boutons de la forme
```javascript
[
 {
   label : "Page d'accueil"
   link : "https://www.systeme-de-design.gouv.fr/"
 },
 ...
]
```

Idéalement on pourrait aussi spécifier des routes dans le format vue-router, comme `{ name: "LandingPage" }` et non seulement des chaînes de caractères indiquant un URL. Comme ça on pourra faire le changement de view avec le router et sans ré-télécharger toute l'application.

```javascript
[
 {
   label : "Page d'accueil"
   to : { name: "LandingPage" }
 },
 {
   label : "Lien externe"
   to : "https://example.com"
 },
 ...
]
```

**Comment by laruiss** [comment]
Bonjour, et merci pour la proposition.

Il s’agit en fait d’une erreur dans notre documentation : chaque élément du tableau de boutons est un objet dont toutes les propriétés seront passées en tant que props à DsfrButton. Or DsfrButton n’accepte pas de prop `link`.

Un slot sera ajouté très prochainement pour donner plus de liberté aux développeurs. Vous pouvez proposer une PR en ce sens si vous souhaitez accélérer le processus 😊

**Comment by laruiss** [comment]
Slot ajouté dans [v5.9.0](https://github.com/dnum-mi/vue-dsfr/releases/tag/v5.9.0)
