### ISSUE TITLE
La propriété "detailIcon" du DsfrCard n'est pas implémentée.

### ISSUE THREAD

**Issue by Forster-Groux** [dnum-mi/vue-dsfr#755]
La propriété `detailIcon` est présente dans la doc mais n'est pas implémentée.

Je pense que dans https://github.com/dnum-mi/vue-dsfr/blob/main/src/components/DsfrCard/DsfrCard.vue
Il suffit de changer ce bout de code :
```
<p
  v-if="detail"
  class="fr-card__detail"
>
  {{ detail }}
</p>
```
par
```
<DsfrCardDetail
  v-if="detail"
  :icon="detailIcon"
>
  {{ detail }}
</DsfrCardDetail>
```
J’essaierai de faire une PR si je trouve un peu de temps.

**Comment by laruiss** [comment]
Merci ! Effectivement ça a l’air d’être un oubli, je corrige ça tout de suite !

**Comment by laruiss** [comment]
Corrigé dans la [5.11.0](https://github.com/dnum-mi/vue-dsfr/releases/tag/v5.11.0)
