### ISSUE TITLE
DsfrFooter: passer des boutons à la props afterMandatoryLinks

### ISSUE THREAD

**Issue by Soufianelt** [dnum-mi/vue-dsfr#771]
Bonjour,
Tout d'abord, merci beaucoup pour votre travail qui facilite grandement notre quotidien sur un projet du MI ! 

Actuellement, il n'est pas possible de passer un bouton dans la liste d'éléments "afterMandatoryLinks" du composant DsfrFooter.
Or Cela nous permettrait d'ouvrir la modale de choix du thème du site et d'être conforme aux recommandations du Dsfr.
(Capture d'écran issue du site du Dsfr https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/parametre-d-affichage/ )

![image](https://github.com/dnum-mi/vue-dsfr/assets/108264787/225cbaa7-c11d-436d-acb8-a17bdfa4781d)

Merci d'avance !

**Comment by laruiss** [comment]
Ajouté dans la [5.11.0](https://github.com/dnum-mi/vue-dsfr/releases/tag/v5.11.0)
