### ISSUE TITLE
[DsfrHeader] Permettre l'ajout d'un sélecteur de langue dans l'en-tête

### ISSUE THREAD

**Issue by cailliaud** [dnum-mi/vue-dsfr#781]
Hello 😄 , de retour sur l'usage du DSFR en vue après quelques mois sur du React. Je suis sur un projet d'une autre entité du ministère cette fois-ci. Et voilà qu'un besoin d'i18n pointe son nez et du coup petite demande pour la gestion du sélecteur.

# TL&DR

Pouvoir injecter un DsfrLanguageSelector dans le DsfrHeader.

# Détails

L'objectif est d'avoir dans la nav du header, le sélecteur de langue comme proposée par le design system (https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/selecteur-de-langue)
![image](https://github.com/dnum-mi/vue-dsfr/assets/19285360/26582ecd-3de5-4079-8c6b-b65209fae3a0)

# Solution(s) proposée(s)

Sur la même base que l'ajout possible du DsfrNavigation via un slot, avoir un slot pour le DsfrLanguageSelector  dans le header.  
Par contre, avoir un alignement des quicklinks avec le selecteur va peut être posé problème.

# Workaround

En attendant, pour gérer la sélection de la locale dans le DsfrHeader, il est possible d'utiliser un quickLink avec un event sur le onClick qui toggle la locale à la suivante.

**Comment by laruiss** [comment]
OK, je m’en occupe

**Comment by laruiss** [comment]
Présent dans la [v5.13.0](https://github.com/dnum-mi/vue-dsfr/releases/tag/v5.13.0)

Cf. la doc de [DsfrHeader](https://vue-ds.fr/composants/DsfrHeader) et du [DsfrLanguageSelector](https://vue-ds.fr/composants/DsfrLanguageSelector)

**Comment by cailliaud** [comment]
Merci @laruiss pour ton efficacité !
