### ISSUE TITLE
[DsfrHeader <-> DsfrHeaderMenuLinks] Éviter la répétition de la balise nav dans le Header

### ISSUE THREAD

**Issue by gweill-guigops** [dnum-mi/vue-dsfr#783]
La balise nav est répétée, une première fois dans le composant DsfrHeader puis une seconde dans DsfrHeaderMenuLinks, ce qui pose un problème d'accessibilité.

https://github.com/dnum-mi/vue-dsfr/blob/ac8f6be1b047611212f3f1ee661c1ac56c809e99/src/components/DsfrHeader/DsfrHeader.vue#L172

https://github.com/dnum-mi/vue-dsfr/blob/ac8f6be1b047611212f3f1ee661c1ac56c809e99/src/components/DsfrHeader/DsfrHeaderMenuLinks.vue#L29

**Comment by laruiss** [comment]
Merci pour le signalement, je m’en occupe très vite !

**Comment by laruiss** [comment]
Corrigé dans la [v5.13.0](https://github.com/dnum-mi/vue-dsfr/releases/tag/v5.13.0)

**Comment by gweill-guigops** [comment]
Merci de votre réactivité !
