### ISSUE TITLE
Erreur sur la doc netlify du composant DsfrCard

### ISSUE THREAD

**Issue by pletelli** [dnum-mi/vue-dsfr#790]
Ici  https://github.com/dnum-mi/vue-dsfr/blob/f0470abd2875a188da64e4b909311298c8b9e2c3/src/components/DsfrCard/DsfrCard.stories.ts#L273    
`<template #interactive-details>`
doit être changé en `<template #start-details>`

**Comment by laruiss** [comment]
Merci !
