### ISSUE TITLE
Rendre le pageCount du composant DsfrTable react à la props rows

### ISSUE THREAD

**Issue by benjaminDNUM** [dnum-mi/vue-dsfr#791]
Ajourd'hui, en cas de modification sur les `rows` d'un `DsfrTable`, la ref `pageCount` ne semble pas mise a jour. Le seul watcher que j'ai vu créant la reactivité sur cette ref est le suivant : 

```
watch(
  () => optionSelected.value,
  (newVal) => {
    pageCount.value =
      props.rows.length > optionSelected.value ? Math.ceil(props.rows.length / newVal) : 1
  },
)
```
(https://vue-ds.fr/composants/DsfrTable)

Cela crée des problemes par exemple lorsque l'on ajoute des elements au tableau. Imaginons un tableau avec une pagination de 10 rows par page. Le table contient 10 éléments et un utilisateur en ajoute un 11eme. Le nombre total de page restera inchangé à 1 au lieu de 2 maintenant.

Il faudrait créer cette réactivité

**Comment by laruiss** [comment]
Bonjour, je veux bien me pencher sur ce problème, cependant, je vous déconseille d’utiliser la pagination dans le composant DsfrTable car il a été implémenté d’une façon expérimentale (et pas très accessible).
Il vaut mieux utiliser DsfrTable et DsfrPagination vous-même.

**Comment by benjaminDNUM** [comment]
> Bonjour, je veux bien me pencher sur ce problème, cependant, je vous déconseille d’utiliser la pagination dans le composant DsfrTable car il a été implémenté d’une façon expérimentale (et pas très accessible). Il vaut mieux utiliser DsfrTable et DsfrPagination vous-même.

Bien noté :) merci beaucoup !

**Comment by laruiss** [comment]
Utiliser plutôt le nouveau composant DsfrDataTable pour embarquer la pagination. Cf. [doc](https://vue-ds.fr/composants/DsfrDataTable)
