### ISSUE TITLE
Prop `readonly` sur DsfrInputGroup

### ISSUE THREAD

**Issue by alemangui** [dnum-mi/vue-dsfr#798]
Bonjour, j'ai peut-être mal compris la doc, mais dans celle concernant [DsfrInputGroup](https://vue-dsfr.netlify.app/?path=/docs/composants-dsfrinputgroup--docs) on a un param `readonly` qui ne semble avoir aucun effet sur les champs à l'intérieur. 

Par contre, au niveau des [DsfrInput](https://vue-dsfr.netlify.app/?path=/docs/composants-dsfrinput--docs) le paramètre `readonly` a bien l'effet désiré, mais la doc ne le mentionne pas.

**Comment by laruiss** [comment]
Bonjour, en effet.
Pour [DsfrInput](https://vue-dsfr.netlify.app/?path=/docs/composants-dsfrinput--docs) que je vous conseille plutôt de regarder [ici](https://vue-ds.fr/composants/DsfrInput), toutes les props qui seront ajoutées à `<DsfrInput />` et qui ne seront pas défini dans les props de DsfrInput seront ajoutés (par `$attrs`) sur la balise native `<input >` du composant. Ce n’est pas le cas pour DsfrInputGroup.
Je vais m’occuper de cela. Merci !

**Comment by laruiss** [comment]
Voilà, c’est fait. Cf [vue-ds.fr](https://vue-ds.fr/composants/DsfrInput#attributs-implicitement-declares)
