### ISSUE TITLE
🐛 DsfrModal: espace en amont du titre

### ISSUE THREAD

**Issue by cailliaud** [dnum-mi/vue-dsfr#809]
Un espace supplémentaire est ajouté en amont de la valeur du titre h1 de la modal

Exemple avec l'app de test du vue-dsfr:
https://github.com/dnum-mi/vue-dsfr/blob/94e5a39073aea68d8090088c4205a904b09f8f47/demo-app/App.vue#L305  
Malgré une props à `Notifications`, on voit bien le h1 avec un espace en amont ajouté
![image](https://github.com/dnum-mi/vue-dsfr/assets/19285360/3de3a1dd-6d34-402a-9029-39ec2e4d9edd)

Résultat: ` Notifications`

Il doit y avoir un espace non souhaité lié au formatage: https://github.com/dnum-mi/vue-dsfr/blob/94e5a39073aea68d8090088c4205a904b09f8f47/src/components/DsfrModal/DsfrModal.vue#L136

**Comment by laruiss** [comment]
Corrigé dans la [v5.17.0](https://github.com/dnum-mi/vue-dsfr/releases/tag/v5.17.0)
