### ISSUE TITLE
Problème ergonomie démonstration

### ISSUE THREAD

**Issue by cesar-lizurey** [dnum-mi/vue-dsfr#825]
C'est peut-être un détail pour vous mais pour moi ça veut dire beaucoup: https://demo.vue-ds.fr/side-menu
Quand on sélectionne "menu latéral" il y a bien le trait bleu sous cet élément, mais quand on sélectionne un titre (quel que soit le niveau), ça semble perdre le focus.
Je n'ai pas regardé en détails le code mais j'ai l'impression qu'il met le focus sur un élément selon l'URL. Il serait sans doute opportun d'utiliser un "startsWith".
Bonne journée à vous.

**Comment by laruiss** [comment]
Cela utilise bien l’URL du lien, et c’est bien ce que l’on veut. Qu’entendez-vous par « ça semble perdre le focus » ?

**Comment by cesar-lizurey** [comment]
Voilà ce qu'on obtient quand on clique sur un élément du menu horizontal en haut puis sur un élément dans la page affichée:

![vue1](https://github.com/dnum-mi/vue-dsfr/assets/63406058/b4e35731-a664-488e-8735-08160800aa87)

On voit bien que le "focus" (pas au sens HTML du terme) est toujours sur l'élément horizontal du menu, même si on a cliqué sur quelque chose en-dessous. Par "focus" j'entends le trait bleu qui souligne l'élément du menu actuel.

En revanche, voilà l'anomalie ergonomique pour "Menu latéral":

![vue2](https://github.com/dnum-mi/vue-dsfr/assets/63406058/8b1548ee-2a4f-4cd1-9c1e-1f663e63908b)

Ici on a bien le "focus" où il faut, mais si on clique sur un élément dans la page en-dessous, le focus se perd (i.e. la barre bleue ne souligne plus l'élément actuel).

![vue3](https://github.com/dnum-mi/vue-dsfr/assets/63406058/dbc2ce93-fc7d-4a0b-8c4a-85df7f836aac)

Est-ce que mes explications supplémentaires vous éclairent un peu plus?

**Comment by laruiss** [comment]
Oui, c’est plus clair. Il ne s’agit pas de focus, il s’agit de la signalisation pour l’utilisateur de la page courante. Et tout est normal. C’est une application de démo, et ça n’a pas vraiment de sens de mettre le même lien dans un menu horizontal comme c’est le cas ici. J’espère que vous comprendrez, je ne vais pas travailler dessus, car ce n’est ni important, ni urgent. Les composants fonctionnent comme ils doivent.
