### ISSUE TITLE
[DSFR Tabs] Uncaught TypeError: event is undefined

### ISSUE THREAD

**Issue by alemangui** [dnum-mi/vue-dsfr#827]
Bonjour,

En utilisant le composant DsfrTabs, si on utilise la touche _Tab_ du clavier pour rendre le focus dans l'onglet d'après, une exception se lève car l'event levé est `undefined`.

C'est assez simple de le reproduire en allant sur https://vue-dsfr.netlify.app/?path=/docs/composants-dsfrtabs--docs, si on navigue sur les exemples en utilisant la tabulation on a cette erreur :

![image](https://github.com/dnum-mi/vue-dsfr/assets/1225929/f867f629-e0ad-482f-9f24-3279df86262b)

**Comment by alemangui** [comment]
Merci pour votre réponse @laruiss, en effet sur vue-ds.fr le comportement n'est pas le même.

Je ne suis pas sur de comprendre la différence entre les deux sites de documentation, s'agit-il des mêmes versions de la lib ? faut-il plutôt que je privilégie vue-ds.fr ?

**Comment by laruiss** [comment]
C'est la même bibliothèque et la petite version (la dernière publiée) qui est utilisée sur les deux sites.
Comme noté dans le storybook, il est préférable d'utiliser la nouvelle documentation plutôt que le Storybook.
Av3c storybook, le code de demo n'est pas aussi isolé que dans la nouvelle doc.

**Comment by alemangui** [comment]
@laruiss au temps pour moi, le bug est bien présent sur la nouvelle doc aussi - c'est juste caché dans la console : 

![image](https://github.com/dnum-mi/vue-dsfr/assets/1225929/e3a364e5-aca0-4f71-8a60-143d76286974)

**Comment by laruiss** [comment]
Très bien, merci de l'avoir signalé.
Je regarde cela dès que possible !

**Comment by laruiss** [comment]
Corrigé dans [v5.18.0](https://github.com/dnum-mi/vue-dsfr/releases/tag/v5.18.0)
