### ISSUE TITLE
MAJ la doc du composant DsfrFileUpload pour limiter le type de fichier 

### ISSUE THREAD

**Issue by leihuayi** [dnum-mi/vue-dsfr#874]
Le [composant DsfrFileUpload](https://vue-dsfr.netlify.app/?path=/docs/composants-dsfrfileupload--docs) accepte toujours tous les types de fichiers.
Il serait bien de pouvoir rajouter un attribut "accept" pour choisir si l'on veut restreindre le type de fichiers pouvant être uploadés comme pour un input classique : https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file.

[EDIT] Apparemment c'est déjà le cas, mais ce n'est pas renseigné dans la doc, il faudrait donc mettre à jour la doc à ce propos.

Par exemple

```
const acceptedTypes = "image/png, image/jpeg"

<template>
  <DsfrFileUpload
    :id="id"
    :label="label"
    :hint="hint"
    :error="error"
    :accept="acceptedTypes"
    :validMessage="validMessage"
    :disabled="disabled"
  />
</template>
```

![image](https://github.com/user-attachments/assets/5b5ec4d9-5f68-42d2-8616-fec5101c3c6d)

**Comment by laruiss** [comment]
C’est déjà le cas.
Tu peux donc déjà écrire presque ce que tu as mis en exemple et ça va fonctionner. Il faut cependant que la valeur passée soit un tableau (ce que je peux modifier).

```js
const acceptedTypes = "image/png, image/jpeg".split(', ')
```

Et ce sera bon. Dans la prochaine version je pense de cet après-midi, on pourra passer une chaîne.

**Comment by leihuayi** [comment]
Hello, sous type de tableau ça va très bien aussi, c'est juste que ce n'était pas dans la doc donc je ne savais pas que c'était possible ! Je vais tester ! Je convertis donc cette tâche en tâche de doc

**Comment by laruiss** [comment]
Doc [améliorée](https://github.com/dnum-mi/vue-dsfr/pull/933/commits/12355a57434ce25690f78b3eb07dd32706f35570)

Merci pour votre retour !
