### ISSUE TITLE
DsfrRadioButtonSet: Bug docs, impossible de choisir une option quand il y a un message erreur/succès 

### ISSUE THREAD

**Issue by hfroot** [dnum-mi/vue-dsfr#881]
Quand je vais à https://vue-ds.fr/composants/DsfrRadioButtonSet#%F0%9F%93%9D-exemples

Je ne peux pas choisir (ni en cliquant, ni avec le clavier) une option pour les ButtonSets avec un message d'erreur ou succès. Je peux choisir une option quand il n'y pas de message

![Screenshot 2024-07-24 at 19-19-37 Groupe de Bouton radio (et bouton radio riche) - DsfrRadioButtonSet VueDsfr](https://github.com/user-attachments/assets/a0bdc152-9fa0-4bf4-ae4c-57dbecc4ee68)

J'ai testé avec Firefox (version 107.0 64-bit pour Fedora) et Chrome (126.0.6478.182)

**Comment by laruiss** [comment]
Je ne sais pas quand, mais cela a été corrigé (en tout cas je ne vois pas le problème sur la documentation actuelle)
