### ISSUE TITLE
DsfrRadioButtonSet : mal alignement de message d'erreur/succès

### ISSUE THREAD

**Issue by hfroot** [dnum-mi/vue-dsfr#882]
https://vue-ds.fr/composants/DsfrRadioButtonSet

![Screenshot 2024-07-25 at 17-09-20 Groupe de Bouton radio (et bouton radio riche) - DsfrRadioButtonSet VueDsfr](https://github.com/user-attachments/assets/be204a0e-a0f2-49a0-83ec-6d3946f17a42)

J'attends le message d'erreur d'être plus haut que le bordeur à gauche, comme pour DsfrInputGroup

https://vue-ds.fr/composants/DsfrInputGroup
![Screenshot 2024-07-25 at 17-10-54 Groupe de champs de saisie - DsfrInputGroup VueDsfr](https://github.com/user-attachments/assets/e30a1212-dc96-4d93-9b82-3d92911831a5)

**Comment by laruiss** [comment]
Corrigé, sera dans la prochaine version
