### ISSUE TITLE
DSFRFooter - RGAA : Manque de l'attribut title sur les liens externe

### ISSUE THREAD

**Issue by RLE-Oui** [dnum-mi/vue-dsfr#884]
Bonjour,

Il manque la possibilité d'ajouter un attribut 'title' à certains lien du footer, notamment sur les 'ecosystemLinks' et le lien vers la licence s'il est externe. Selon le critère 6.1 du RGAA un lien doit indiqué sa fonction et sa destination, pas de souci dans le cas d'un lien interne mais pour les liens externe il faut le préciser par exemple de cette façon : title="INTITULÉ VISIBLE, nouvelle fenêtre".

Bonne journée

**Comment by laruiss** [comment]
Corrigé, sera dans la prochaine release.
