### ISSUE TITLE
DsfrHeader : pas de lien vers homeTo si il n'y a pas de serviceTitle

### ISSUE THREAD

**Issue by hfroot** [dnum-mi/vue-dsfr#889]
## Problème

Quand `serviceTitle` n'est pas donné au `DsfrHeader`, on ne peut pas ajouter un lien `homeTo` (et le defaut de `"/"` ne marche pas non plus).

Extrait de AppHeader.vue :

```
            <div
              v-if="serviceTitle"
              class="fr-header__service"
            >
              <RouterLink
                :to="homeTo"
                :title="`${homeLabel} - ${serviceTitle}`"
                v-bind="$attrs"
              >
```

C'est la seule utilisation de `homeTo` que je vois dans ce fichier, alors si `serviceTitle` n'est pas utilisé, il y a pas de lien mais il y a toujours un changement de la couleur de fond quand on survol sur le logo.

On voit ce comportement dans le site exemple de vue DSFR : https://demo.vue-ds.fr/

![Screenshot 2024-08-14 at 13-17-30 Demo VueDSFR](https://github.com/user-attachments/assets/a9dadc6d-5826-4f1d-8726-2ff9fb319ee1)

## Comportement voulu

L'option d'utiliser `homeTo` sans `serviceTitle`.

**Comment by laruiss** [comment]
Corrigé [ici](https://github.com/dnum-mi/vue-dsfr/pull/935/commits/712a2593cc99d11eccfa1acf8016c033fafabc42). Sera dans la prochaine release.
