### ISSUE TITLE
Documentation : DsfrHeaderMenuLink ne prend pas href

### ISSUE THREAD

**Issue by hfroot** [dnum-mi/vue-dsfr#890]
Dans les docs `href` est noté comme un attribut possible. https://vue-ds.fr/composants/DsfrHeaderMenuLink

![Screenshot 2024-08-14 at 13-32-41 Lien d’en-tête - DsfrHeaderMenuLink VueDsfr](https://github.com/user-attachments/assets/eafcce42-9686-4029-81fa-b587cb7dc42c)

Mais dans le code je vois que c'est géré par `to` : https://github.com/dnum-mi/vue-dsfr/blob/main/src/components/DsfrNavigation/DsfrNavigationMenuLink.vue

`const isExternal = computed(() => typeof props.to === 'string' && props.to.startsWith('http'))`

**Comment by laruiss** [comment]
En effet, c’est un oubli dans la doc : `href` a été déprécié, puis retiré et la doc n’a pas été mise à jour, je m’en occupe dès que possible.

**Comment by laruiss** [comment]
Attention : `href` est encore géré dans [`DsfrHeaderMenuLink`](https://vue-ds.fr/composants/DsfrHeaderMenuLink#%E2%9A%99%EF%B8%8F-code-source-du-composant) mais c’est seulement `to` qui est géré dans `DsfrNavigationMenuLink` (qui peut être intégré dans le Header...).
Je modifie DsfrHeaderMenuLink pour déprécier href aussi dans ce composant.

**Comment by laruiss** [comment]
Corrigé
