### ISSUE TITLE
DsfrHeader : gestion de logout

### ISSUE THREAD

**Issue by hfroot** [dnum-mi/vue-dsfr#892]
J'ai une question/suggestion pour une amélioration : avant Vue DSFR on a donné nos utilisateurs l'option de se deconnecter depuis un modal qui est ouvert via un bouton qui rassemble un quick link. Le bouton pour confirmer le logout dans le model envoie un POST vers notre back.

![Screenshot 2024-08-14 at 14-01-46 ma cantine](https://github.com/user-attachments/assets/aca2c783-a6dc-47b7-ba0b-8a4f9e0b289c)
![Screenshot 2024-08-14 at 14-02-00 ma cantine](https://github.com/user-attachments/assets/5db3fd83-00b3-43ca-99b2-f5876b853902)

Je pense que c'est pas possible en ce moment de créer un équivalent avec le composant DsfrHeader, alors je demande si on pourrait ajouter une option similaire ?

Sinon, est-ce qu'il y a un conseil de comment gérer le logout ?

**Comment by laruiss** [comment]
Est-ce que cette [recette de la documentation](https://vue-ds.fr/recettes/bouton-dans-header) répond à votre besoin ?

**Comment by hfroot** [comment]
Merci ! Je crois que oui
