### ISSUE TITLE
DsfrCheckboxSet : attribut `value` ignoré

### ISSUE THREAD

**Issue by CopperGiraffe** [dnum-mi/vue-dsfr#893]
Salut l’équipe vue-dsfr,

Est-ce qu’on ne devrait pas plutôt se baser sur l’attribut `value` pour identifier si une case est cochée dans un CheckboxSet ? 

Pour avoir un fieldset de checkbox en html on peut écrire ça comme ça :
```
<fieldset>
  <legend>Choose your interests</legend>
  <div>
    <input type="checkbox" id="coding" name="interest" value="coding" />
    <label for="coding">Coding</label>
  </div>
  <div>
    <input type="checkbox" id="music" name="interest" value="music" />
    <label for="music">Music</label>
  </div>
</fieldset>
```
De cette façon, lors de la soumission du formulaire, on a bien une ou plusieurs valeurs pour le champs qui porte le nom `interest`
(Comme on le retrouve classiquement https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#handling_multiple_checkboxes)

Le problème avec l’implémentation actuelle des CheckboxSet et qu’on vérifie qu’une case est cochée ou non en fonction de l’attribut `name` alors que celui-ci sera le même pour l’ensemble des options

Ce changement peut être impactant, le conditionner sur la présence de l’attribut value dans les options peut mitiger les répercussions.

https://github.com/dnum-mi/vue-dsfr/blob/0b915cd40d73608c3bf1388be8f0b4d7398461e4/src/components/DsfrCheckbox/DsfrCheckboxSet.vue#L79

Si cette solution semble être bonne, je peux faire une PR

**Comment by laruiss** [comment]
Bonjour, et merci pour votre retour.
Vous avez raison, les checkboxes n’ont pas été implémentées de la meilleure des façons.
Je viens de la corriger, cependant, cela fera un breaking change... ce sera donc une version 7.

**Comment by laruiss** [comment]
Corrigé dans la [v7.0.0](https://github.com/dnum-mi/vue-dsfr/releases/tag/v7.0.0)
