### ISSUE TITLE
DsfrRadioButtonSet : ajouter l'option d'utiliser un hint

### ISSUE THREAD

**Issue by hfroot** [dnum-mi/vue-dsfr#899]
Mon problème : je veux indiquer que cette question radio est optionnel en utilisant le hint text.

Contexte : aujourd'hui, pour DsfrRadioButtonSet, c'est que possible d'ajouter un hint avec le slot `legend`

Le DSFR propose qu'on peut utiliser du texte d'aide pour un groupe de boutons radio :

https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/bouton-radio

![Screenshot 2024-08-28 at 12-42-32 Bouton radio - Radio button - Système de Design de l'État](https://github.com/user-attachments/assets/968e50bf-6f5c-403f-8720-4725d75115d4)

En plus, le conseil pour les formulaires c'est de marquer les questions qui sont optionnels comme optionnel :

https://www.systeme-de-design.gouv.fr/composants-et-modeles/blocs-fonctionnels/formulaires

![Screenshot 2024-08-28 at 12-44-07 Formulaires - Système de Design de l'État](https://github.com/user-attachments/assets/302a430f-7714-464b-a19c-fe9298f408ab)

**Comment by laruiss** [comment]
Ajouté dans la [v5.22.0](https://github.com/dnum-mi/vue-dsfr/releases/tag/v5.22.0)
