### ISSUE TITLE
DsfrCard: ajout d'un slot dans le card header permettant l'utilisation de tags ou de badges

### ISSUE THREAD

**Issue by dolemoine** [dnum-mi/vue-dsfr#909]
Notre besoin : ajouter un badge dans le header d'une card, comme présenté dans le Dsfr : 

![image](https://github.com/user-attachments/assets/6e1b841c-8a85-45e6-be39-eb9bca5cfb44)

Aujourd'hui, l'utilisation de badges / tags dans le DsfrCard du vue-dsfr est possible uniquement dans le body.

Pourrait-on imaginer l'ajout d'un slot dans le composant DsfrCard, ou d'un BadgeGroup, qui permettrait cette fonctionalité ?

**Comment by laruiss** [comment]
Ajouté dans la [v5.21.0](https://github.com/dnum-mi/vue-dsfr/releases/tag/v5.21.0)
