### ISSUE TITLE
[DsfrHeader] Absence de fermeture du menu modal en mode mobile lors d'un changement de page

### ISSUE THREAD

**Issue by cailliaud** [dnum-mi/vue-dsfr#926]
Bonjour

## TL&DR
En mode mobile, lorsque l'on clique sur un DsfrHeaderMenuLink cela ne déclenche pas la fermeture du menu modal comme il est prévu par le DSFR.

## Comportement attendu
https://github.com/user-attachments/assets/8a3a0cf2-0929-433a-a48c-a805d185225d

## Exemple Vue-dsfr

https://github.com/user-attachments/assets/83cd32e0-17e6-4326-bd45-8313deb7425a

**Comment by cailliaud** [comment]
Related to #450

**Comment by laruiss** [comment]
Corrigé dans la [6.0.2](https://github.com/dnum-mi/vue-dsfr/releases/tag/v6.1.0)
