### ISSUE TITLE
DsfrTooltip : le tooltip ne s’affiche pas à la prise du focus

### ISSUE THREAD

**Issue by CopperGiraffe** [dnum-mi/vue-dsfr#952]
Salut la team vue-dsfr,

Anomalie remarquée sur le composant DsfrTooltip, celui-ci ne s’affiche pas lorsqu’on le focus, contrairement à ce qu’on peut voir dans la [démo du DSFR](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/infobulle#).

Je remarque également que la touche `esc` ne permet pas de masquer le tooltip comme sur la démo du DSFR ainsi que sur la [recommandation du w3](https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/) (qui ne semble pas tout à fait encore figée cela dit)

Merci par avance et bonne journée !

**Comment by laruiss** [comment]
Merci, ce sera corrigé rapidement
