### ISSUE TITLE
DsfrTooltip provoque une validation des formulaires lors du clic

### ISSUE THREAD

**Issue by vdizengremel** [dnum-mi/vue-dsfr#957]
### Contexte
Bonjour,

Je souhaite utiliser le DsfrTooltip dans un formulaire. Je l'utilise avec la propriété `on-hover` à false. 
`<DsfrTooltip content="Un élément assez intriguant" :on-hover="false" />`

Versions du DS : 
```json
{
    "@gouvfr/dsfr": "1.12.1",
    "@gouvminint/vue-dsfr": "7.0.1",
}
```

### Problème
Le DsfrTootip utilise un `<button>` dans ce cas. Quand on clique dessus, le formulaire est submit alors qu'il devrait simplement afficher l'info bulle sans submit le formulaire.

### Solution
Le bouton n'a pas d'attribut "type" et est donc considéré comme étant un bouton de submit. Il faudrait que le bouton ait l'attribut `type="button"`.

[Thread stackoverflow mentionnant ce problème avec la solution décrite](https://stackoverflow.com/questions/77209871/issue-with-vee-validate-in-vue-3-multiple-button-elements-triggering-form-subm)

J'ai pu tester via chrome en modifiant l'HTML de ma page pour ajouter l'attribut en question sur le bouton et j'ai effectivement le comportement attendu qui est de ne pas provoquer de submit lors du clic sur le composant.

**Comment by laruiss** [comment]
Corrigé dans [v7.0.2](https://github.com/dnum-mi/vue-dsfr/releases/tag/v7.0.2)
