### ISSUE TITLE
Déplacer dépendance pnpm dans `devDependencies`

### ISSUE THREAD

**Issue by Naybnet** [dnum-mi/vue-dsfr#959]
Merci pour cette librairie que nous adoptons au fur et à mesure dans Mon Suivi Social.

Le commit eab95477d8cd567e7ba26931be0e1d28f993b342 ajoute la dépendance à pnpm 9.10. Est-elle vraiment nécessaire en tant que dépendance directe ? Cela nous contraint beaucoup car elle est différente de la version que nous utilisons.

**Comment by laruiss** [comment]
En effet, je vais la mettre dans `devDependencies`, mes excuses.

**Comment by laruiss** [comment]
Corrigé dans [v7.0.2](https://github.com/dnum-mi/vue-dsfr/releases/tag/v7.0.2)
