### ISSUE TITLE
Rendre la clef de localStorage paramétrable pour l'utilisation de useScheme()

### ISSUE THREAD

**Issue by lowzonenose** [dnum-mi/vue-dsfr#968]
Bonjour,
Est il possible de rendre **paramétrable** le nom de la clef du _localStorage_ pour le choix du thème (light / dark / system) ?
cf. https://github.com/dnum-mi/vue-dsfr/blob/cbc986a9dfa438e15b28238eb3027ed1b92ad273/src/composables/useScheme.ts#L5

**Comment by laruiss** [comment]
Fait dans [v7.1.0](https://github.com/dnum-mi/vue-dsfr/releases/tag/v7.1.0)
