### ISSUE TITLE
DsfrHeader : Titre du RouterLink affiche "undefined" si le serviceTitle est vide

### ISSUE THREAD

**Issue by alemangui** [dnum-mi/vue-dsfr#971]
Bonjour,

Sur le DsfrHeader on a la prop optionnelle `serviceTitle`.

Par contre, si on ne set pas cette prop, le tooltip affichera « undefined », par exemple `Accueil - undefined`. Je pense que c'est ce bout de code: 

```html
               <RouterLink
                  :to="homeTo"
                  :title="`${homeLabel} - ${serviceTitle}`"
                >
```

Naïvement je me dis qu'en faisant cette petite modif ça pourrait le régler :
```html
               <RouterLink
                  :to="homeTo"
                  :title="serviceTitle ? `${homeLabel} - ${serviceTitle}` : `${homeLabel}`"
                >
```

**Comment by laruiss** [comment]
Corrigé dans [v7.1.0](https://github.com/dnum-mi/vue-dsfr/releases/tag/v7.1.0)
