### ISSUE TITLE
DsfrDataTable: <caption> est visible même si la propriété no-caption est à true

### ISSUE THREAD

**Issue by paulelian-tabarant** [dnum-mi/vue-dsfr#992]
## Version des dépendances

~~~json
    "@gouvfr/dsfr": "1.13.0",
    "@gouvminint/vue-dsfr": "7.1.1",
~~~

## Description du problème

En effectuant le rendu d'une `DsfrDataTable` comme suit

~~~vue
        <DsfrDataTable
          title="Sélection de l'entité à affecter à l'utilisateur"
          no-caption
          ...
        >
~~~

, le texte passé en `title` s'affiche tout de même à l'écran.

![image](https://github.com/user-attachments/assets/29ae40f7-fba1-4e89-863e-4f779f080a01)

## Comportement attendu

`<caption>` est présente dans le DOM avec le titre mentionné, mais n'est pas visible à l'écran.

**Comment by laruiss** [comment]
Corrigé, sera dans la prochaine release.
