### ISSUE TITLE
DsfrDataTable: le tableau s'affiche à la deuxième page par défaut

### ISSUE THREAD

**Issue by paulelian-tabarant** [dnum-mi/vue-dsfr#993]
## Version des dépendances

~~~json
    "@gouvfr/dsfr": "1.13.0",
    "@gouvminint/vue-dsfr": "7.1.1",
~~~

## Problème constaté

En effectuant le rendu du composant sans la propriété `current-page` comme ci-dessous par exemple, qui prend donc sa valeur par défaut (`1`), le tableau affiche initialement la deuxième page.

### Cas sans aucune ligne dans le tableau

~~~vue
        <DsfrDataTable
         ...
          :rows="[]"
          pagination
        >
~~~

Résultat avec le rendu ci-dessus

![image](https://github.com/user-attachments/assets/21ff0732-1475-4b0a-ac19-9e3356748d1a)

### Cas avec au moins une ligne dans le tableau

~~~vue
        <DsfrDataTable
          ...
          :rows="[{ raisonSociale: "Association les Sapins", siren: "123456789"}]"
          pagination
        >
~~~

Résultat avec le rendu ci-dessus

![image](https://github.com/user-attachments/assets/2f77d7e7-ac18-4170-9174-38b4e135220c)

Pour l'instant, on met la propriété `current-page` à `0` pour être initialement sur la première page.

## Comportement attendu

Initialement, le tableau affiche la première page

![image](https://github.com/user-attachments/assets/ccd50530-cff5-4053-9992-4683b411987e)

**suggestion**: si le tableau fourni à la propriété `rows` en entrée est vide, on pourrait envisager un affichage spécifique ou a minima cacher le footer de navigation entre les pages qui s'affiche en-dessous du tableau

**Comment by laruiss** [comment]
Corrigé : le défaut est maintenant 0. Sera dans la prochaine livraison.
