### ISSUE TITLE
DsfrToggleSwitch : Impossible de définir un `name`

### ISSUE THREAD

**Issue by CopperGiraffe** [dnum-mi/vue-dsfr#994]
Hello l’équipe vue-dsfr,

Le composant DsfrToggleSwitch pose un input de type checkbox dans la page dont il est impossible de définir le name pour la soumission du formulaire. Cela devrait être possible en ajoutant cet attribut.

Merci par avance !

**Comment by laruiss** [comment]
Bonjour, pour récupérer la valeur, il est prévu d’utiliser `v-model`
